// ── Display data (preserved from original planetData) ────────────────────────
export const planetData = {
  sun: {
    name: "SUN",
    symbol: "\u2609",
    subtitle: "Yellow Dwarf Star",
    info: "The heart of our solar system",
    distance: "0",
    diameter: "1,392,000 km",
    period: "\u2014",
    dayLength: "25 Earth days",
    temperature: "5,500\u00b0C (surface)",
    gravity: "28g",
    moons: 0,
    atmosphere: "Hydrogen, Helium",
    facts: [
      "Contains 99.8% of system's mass",
      "Powers all life on Earth",
      "Nuclear fusion reactor at core"
    ]
  },
  "asteroid-belt": {
    name: "ASTEROID BELT",
    symbol: "\u2604",
    subtitle: "Main Belt Region",
    info: "Rocky debris field between Mars and Jupiter",
    distance: "329-478 million km",
    diameter: "~150 million km wide",
    period: "3-6 Earth years (varies)",
    dayLength: "N/A",
    temperature: "-73\u00b0C to -108\u00b0C",
    gravity: "Near zero (individual asteroids)",
    moons: 0,
    atmosphere: "None",
    facts: [
      "Formed from failed planet formation",
      "Jupiter's gravity prevented coalescence",
      "Ceres contains 25% of belt's total mass",
      "Safe for spacecraft (sparse distribution)",
      "Total mass: ~3% of Moon's mass",
      "Over 1.3 million cataloged asteroids"
    ]
  },
  mercury: {
    name: "MERCURY",
    symbol: "\u263f",
    subtitle: "The Swift Planet",
    info: "Smallest planet in solar system",
    distance: "57.9 million km",
    diameter: "4,879 km",
    period: "88 Earth days",
    dayLength: "59 Earth days",
    temperature: "-173\u00b0C to 427\u00b0C",
    gravity: "0.38g",
    moons: 0,
    atmosphere: "None",
    facts: [
      "Fastest orbit around Sun",
      "Extreme temperature swings",
      "Named after Roman messenger god"
    ]
  },
  venus: {
    name: "VENUS",
    symbol: "\u2640",
    subtitle: "Earth's Evil Twin",
    info: "Hottest planet in solar system",
    distance: "108.2 million km",
    diameter: "12,104 km",
    period: "225 Earth days",
    dayLength: "243 Earth days (retrograde)",
    temperature: "462\u00b0C (average)",
    gravity: "0.90g",
    moons: 0,
    atmosphere: "CO\u2082, Sulfuric Acid clouds",
    facts: [
      "Rotates backwards (retrograde)",
      "Day longer than year",
      "Volcanic hellscape"
    ]
  },
  earth: {
    name: "EARTH",
    symbol: "\ud83d\udea8",
    subtitle: "The Blue Planet",
    info: "Our home in the cosmos",
    distance: "149.6 million km",
    diameter: "12,742 km",
    period: "365.25 days",
    dayLength: "24 hours",
    temperature: "-88\u00b0C to 58\u00b0C",
    gravity: "1.0g",
    moons: 1,
    atmosphere: "N\u2082, O\u2082",
    facts: [
      "Only known planet with life",
      "71% covered by water",
      "Perfect conditions for civilization"
    ]
  },
  mars: {
    name: "MARS",
    symbol: "\u2642",
    subtitle: "The Red Planet",
    info: "Future human colony",
    distance: "227.9 million km",
    diameter: "6,779 km",
    period: "687 Earth days",
    dayLength: "24.6 hours",
    temperature: "-140\u00b0C to 20\u00b0C",
    gravity: "0.38g",
    moons: 2,
    atmosphere: "CO\u2082 (thin)",
    facts: [
      "Home to Olympus Mons (tallest mountain)",
      "Ancient riverbeds discovered",
      "Target for human colonization"
    ]
  },
  jupiter: {
    name: "JUPITER",
    symbol: "\u2643",
    subtitle: "King of Planets",
    info: "Largest planet in solar system",
    distance: "778.5 million km",
    diameter: "139,820 km",
    period: "11.9 Earth years (4,333 days)",
    dayLength: "10 hours",
    temperature: "-145\u00b0C (cloud tops)",
    gravity: "2.5g",
    moons: 79,
    atmosphere: "H\u2082, He",
    facts: [
      "Great Red Spot storm (300+ years old)",
      "Protects Earth from asteroids",
      "Could contain 1,300 Earths"
    ]
  },
  saturn: {
    name: "SATURN",
    symbol: "\u2644",
    subtitle: "Lord of the Rings",
    info: "Most spectacular ring system",
    distance: "1.4 billion km",
    diameter: "116,460 km",
    period: "29.5 Earth years (10,759 days)",
    dayLength: "10.7 hours",
    temperature: "-178\u00b0C",
    gravity: "1.1g",
    moons: 82,
    atmosphere: "H\u2082, He",
    facts: [
      "Rings made of ice and rock",
      "Low density (would float on water)",
      "Hexagonal storm at north pole"
    ]
  },
  uranus: {
    name: "URANUS",
    symbol: "\u2645",
    subtitle: "The Sideways Planet",
    info: "Ice giant with extreme tilt",
    distance: "2.9 billion km",
    diameter: "50,724 km",
    period: "84 Earth years (30,687 days)",
    dayLength: "17.2 hours (retrograde)",
    temperature: "-224\u00b0C",
    gravity: "0.89g",
    moons: 27,
    atmosphere: "H\u2082, He, CH\u2084",
    facts: [
      "Rotates on its side (98\u00b0 tilt)",
      "Faint ring system",
      "Methane gives blue-green color"
    ]
  },
  neptune: {
    name: "NEPTUNE",
    symbol: "\u2646",
    subtitle: "The Windy World",
    info: "Fastest winds in solar system",
    distance: "4.5 billion km",
    diameter: "49,244 km",
    period: "165 Earth years (60,190 days)",
    dayLength: "16 hours",
    temperature: "-214\u00b0C",
    gravity: "1.1g",
    moons: 14,
    atmosphere: "H\u2082, He, CH\u2084",
    facts: [
      "Winds reach 2,100 km/h",
      "Dark Spot storms",
      "Discovered by mathematics"
    ]
  },
  pluto: {
    name: "PLUTO",
    symbol: "\u2647",
    subtitle: "The Heart of Ice",
    info: "Dwarf planet in Kuiper Belt",
    distance: "5.9 billion km",
    diameter: "2,377 km",
    period: "248 Earth years (90,560 days)",
    dayLength: "6.4 Earth days",
    temperature: "-229\u00b0C",
    gravity: "0.06g",
    moons: 5,
    atmosphere: "N\u2082, CH\u2084 (seasonal)",
    facts: [
      "Heart-shaped ice plain (Tombaugh Regio)",
      "Reclassified as dwarf planet (2006)",
      "Five moons in complex dance"
    ]
  },
  // ── Stellar Remnants ──
  siriusA: {
    name: "SIRIUS A",
    symbol: "\u2609",
    subtitle: "Brightest Star in Night Sky",
    info: "A-type main sequence star, 25x brighter than Sun",
    distance: "8.6 light-years",
    diameter: "2,400,000 km (1.7x Sun)",
    period: "\u2014",
    dayLength: "~5 Earth days",
    temperature: "9,940\u00b0C (surface)",
    gravity: "4.3g (surface)",
    moons: 0,
    atmosphere: "Hydrogen, helium (fusion core)",
    facts: [
      "Brightest star visible from Earth",
      "Called 'Dog Star' - part of Canis Major",
      "Only 2x Sun's mass but 25x brighter",
      "Will become red giant in ~1 billion years",
      "Sirius B orbits it every 50 years",
      "Rises with Sun in summer (dog days)",
      "Visible from almost entire Earth"
    ]
  },
  siriusB: {
    name: "SIRIUS B",
    symbol: "\u2609",
    subtitle: "White Dwarf Star",
    info: "Earth-sized star with solar mass, companion to Sirius A",
    distance: "8.6 light-years",
    diameter: "11,684 km (0.84x Earth)",
    period: "50.1 years (binary orbit)",
    dayLength: "Unknown (rotating)",
    temperature: "25,200\u00b0C (surface)",
    gravity: "350,000g (surface)",
    moons: 0,
    atmosphere: "Carbon/oxygen core, helium envelope",
    facts: [
      "Most massive white dwarf known: 0.98 solar masses",
      "Same size as Earth but mass of our Sun",
      "Discovered 1862 by Alvan Clark",
      "Will cool into black dwarf over trillions of years",
      "Was a main-sequence star 120 million years ago",
      "Companion Sirius A is brightest star in night sky"
    ]
  },
  velaPulsar: {
    name: "VELA PULSAR",
    symbol: "\u2726",
    subtitle: "Neutron Star (Pulsar)",
    info: "Rotating neutron star emitting beams of radiation",
    distance: "936 light-years",
    diameter: "~20 km (city-sized)",
    period: "89.3 milliseconds (rotation)",
    dayLength: "11 rotations per second",
    temperature: "1,000,000\u00b0C (surface)",
    gravity: "100,000,000,000g (surface)",
    moons: 0,
    atmosphere: "None (pure neutron matter crust)",
    facts: [
      "Spins 11 times per second, emitting lighthouse beams",
      "Supernova remnant from 11,000 years ago",
      "One sugar-cube of matter weighs 1 billion tons",
      "Magnetic field 1 trillion times stronger than Earth's",
      "Visible to naked eye in very dark skies",
      "Proves prediction of neutron stars (1934 Landau)",
      "Part of Vela Supernova Remnant in southern sky"
    ]
  },
  sagittariusA: {
    name: "SAGITTARIUS A*",
    symbol: "\u2605",
    subtitle: "Supermassive Black Hole",
    info: "4 million solar mass monster at Milky Way's center",
    distance: "26,673 light-years",
    diameter: "51.8 million km (event horizon)",
    period: "Rotation ~10 minutes (near light speed)",
    dayLength: "Inapplicable (frozen time at horizon)",
    temperature: "Absolute zero (hawking radiation ~10^-7 K)",
    gravity: "Infinite at singularity",
    moons: 0,
    atmosphere: "Accretion disk of superheated plasma",
    facts: [
      "First black hole imaged by EHT in 2022",
      "4.3 million times the mass of our Sun",
      "Event horizon diameter equals Mercury's orbit",
      "Surrounded by hot gas swirling at 30% light speed",
      "S-stars orbit it at 3% light speed",
      "Discovered via radio emissions in 1974",
      "Accretion disk glows at millions of degrees",
      "Controls rotation of entire Milky Way galaxy"
    ]
  },
  // ── TRAPPIST-1 Exoplanet System ──
  trappist1: {
    name: "TRAPPIST-1",
    symbol: "\u2609",
    subtitle: "Ultra-Cool Red Dwarf Star",
    info: "Host star to 7 Earth-sized rocky planets",
    distance: "39 light-years",
    diameter: "160,000 km (0.12x Sun)",
    period: "\u2014",
    dayLength: "3.3 Earth days",
    temperature: "2,566\u00b0C (surface)",
    gravity: "0.08g (surface)",
    moons: 0,
    atmosphere: "Hydrogen (red dwarf)",
    facts: [
      "Discovered 2010 by TRAPPIST telescope in Chile",
      "Planets discovered 2015-2017 by Spitzer Space Telescope",
      "All 7 planets could potentially have liquid water",
      "3 planets in habitable zone (b, c, d)",
      "Star is barely larger than Jupiter",
      "Planets are gravitationally locked (tidally)",
      "Perfect target for JWST atmospheric studies",
      "Most studied planetary system beyond our own"
    ]
  },
  trappist1b: {
    name: "TRAPPIST-1b",
    symbol: "b",
    subtitle: "Rocky Exoplanet",
    info: "Hot world 100x closer to star than Earth",
    distance: "1.5 million km from TRAPPIST-1",
    diameter: "11,553 km (0.9x Earth)",
    period: "1.5 Earth days",
    dayLength: "Tidally locked (1.5 days)",
    temperature: "~400\u00b0C (dayside)",
    gravity: "0.85g",
    moons: 0,
    atmosphere: "Likely lost to stellar wind",
    facts: [
      "Too hot for liquid water, likely Venus-like",
      "Tidally locked: one side always faces star",
      "Orbit period just 36 hours",
      " receives 4x more radiation than Mercury",
      "JWST detected no significant atmosphere",
      "Surface may be volcanic or desert",
      "Innermost of 7 known planets"
    ]
  },
  trappist1e: {
    name: "TRAPPIST-1e",
    symbol: "e",
    subtitle: "Potentially Habitable Exoplanet",
    info: "Best candidate for habitability in the system",
    distance: "4.3 million km from TRAPPIST-1",
    diameter: "9,140 km (0.72x Earth)",
    period: "6.1 Earth days",
    dayLength: "Tidally locked (6.1 days)",
    temperature: "-20\u00b0C to 40\u00b0C (estimated)",
    gravity: "0.93g",
    moons: 0,
    atmosphere: "Unknown (under study by JWST)",
    facts: [
      "Most similar to Earth in radiation received",
      "Rocky world slightly smaller than Earth",
      "In habitable zone where water could be liquid",
      "May have thin atmosphere like Mars",
      "JWST searching for CO2, water vapor, methane",
      "Twilight zone could be most habitable",
      "Future target for direct imaging",
      "Could have subsurface oceans"
    ]
  },
  trappist1f: {
    name: "TRAPPIST-1f",
    symbol: "f",
    subtitle: "Water World Candidate",
    info: "Likely global ocean or thick ice shell",
    distance: "5.7 million km from TRAPPIST-1",
    diameter: "10,400 km (0.82x Earth)",
    period: "9.2 Earth days",
    dayLength: "Tidally locked (9.2 days)",
    temperature: "-50\u00b0C to 0\u00b0C (estimated)",
    gravity: "0.68g",
    moons: 0,
    atmosphere: "Unknown (possibly thick CO2)",
    facts: [
      "Likely covered in global ocean or ice",
      "Could have 20x Earth's water content",
      "Just outside inner edge of habitable zone",
      "May be 'eyeball planet' with ice and water",
      "Thick atmosphere possible for heat retention",
      "Rocky core under deep water layer",
      "Potential subsurface ocean habitat",
      "Best candidate for water detection"
    ]
  },
  // ── Massive Stars & Supergiants ──
  betelgeuse: {
    name: "BETELGEUSE",
    symbol: "\u2605",
    subtitle: "Red Supergiant Star",
    info: "Monster star 700x larger than our Sun, nearing supernova",
    distance: "642.5 light-years",
    diameter: "1,234,000,000 km (887x Sun, 9.5 AU)",
    period: "\u2014",
    dayLength: "~1000 Earth days (very slow rotation)",
    temperature: "3,500\u00b0C (surface)",
    gravity: "0.0005g (surface)",
    moons: 0,
    atmosphere: "Extended stellar envelope of gas",
    facts: [
      "If placed at Sun's center, surface would reach Jupiter",
      "Expected to explode as supernova within 100,000 years",
      "Mass ~20x Sun but 700x larger radius",
      "2019 'Great Dimming' was dust cloud ejection",
      "Visible as red star in Orion constellation",
      "One of largest stars visible to naked eye",
      "Surface would extend past asteroid belt",
      "Fusion produces heavy elements: carbon to iron"
    ]
  },
  r136a1: {
    name: "R136a1",
    symbol: "\u2605",
    subtitle: "Most Massive Known Star",
    info: "Wolf-Rayet star 196x more massive than our Sun",
    distance: "163,000 light-years (Large Magellanic Cloud)",
    diameter: "~10,000,000 km (14x Sun)",
    period: "\u2014",
    dayLength: "~6 Earth days",
    temperature: "53,000\u00b0C (surface)",
    gravity: "~10g (surface)",
    moons: 0,
    atmosphere: "Extreme stellar wind stripping outer layers",
    facts: [
      "Most massive known star: 196 solar masses",
      "Brightness: 4.6 million times our Sun",
      "Will become black hole in ~2 million years",
      "Located in Tarantula Nebula outside Milky Way",
      "Strong stellar winds at 3,000 km/s",
      "Likely formed by stellar merger",
      "Hundreds of times more massive than 'normal' stars",
      "Will produce hypernova explosion, brightest in universe"
    ]
  },
  // ── Black Holes ──
  ton618: {
    name: "TON 618",
    symbol: "\u25C9",
    subtitle: "Hypermassive Quasar Black Hole",
    info: "66 billion solar masses — one of the universe's most massive black holes",
    distance: "10.4 billion light-years",
    diameter: "390 billion km (event horizon)",
    period: "Inapplicable (frozen at horizon)",
    dayLength: "Inapplicable",
    temperature: "~10\u00b9\u00b2 K (accretion disk)",
    gravity: "Infinite at singularity",
    moons: 0,
    atmosphere: "Superheated quasar jet plasma",
    facts: [
      "66 billion solar masses — among universe's most massive BHs",
      "Luminosity: 4\u00d710\u00b3\u2079 watts — 140 trillion times the Sun",
      "Event horizon: 1,300\u00d7 the Earth-Sun distance",
      "Powers a quasar brighter than entire galaxies",
      "Light from it took 10.4 billion years to reach us",
      "Formed when the universe was only 3 billion years old",
      "Would take light 190 days to cross its event horizon",
      "Located in galaxy CVn I dwarf at redshift z=2.219"
    ]
  },
  m87bh: {
    name: "M87\u2217",
    symbol: "\u25C9",
    subtitle: "First Photographed Black Hole",
    info: "6.5 billion solar mass giant at M87 galaxy's center",
    distance: "53.5 million light-years",
    diameter: "38 billion km (event horizon)",
    period: "~2 years (inner accretion orbit)",
    dayLength: "Inapplicable",
    temperature: "~10\u00b9\u00b2 K (accretion disk)",
    gravity: "Infinite at singularity",
    moons: 0,
    atmosphere: "Relativistic jet extending 5,000 light-years",
    facts: [
      "First black hole ever directly imaged — April 10, 2019",
      "Event Horizon Telescope array photographed its shadow",
      "6.5 billion solar masses — 1,600\u00d7 Sagittarius A\u2217",
      "Ejects a relativistic plasma jet 5,000 light-years long",
      "Jet plasma travels at 99% the speed of light",
      "Located in elliptical galaxy M87 in Virgo constellation",
      "Ring image: glowing superheated plasma swirling in",
      "Shadow diameter is 2.5\u00d7 larger than Pluto's orbit around Sun"
    ]
  },
  cygnusX1: {
    name: "CYGNUS X-1",
    symbol: "\u25C9",
    subtitle: "Stellar-Mass Black Hole",
    info: "First confirmed black hole — 21 solar masses in binary system",
    distance: "7,200 light-years",
    diameter: "~350 km (Schwarzschild radius)",
    period: "5.6 Earth days (binary orbit)",
    dayLength: "Inapplicable",
    temperature: ">10\u2077 K (accretion disk)",
    gravity: "Infinite at singularity",
    moons: 0,
    atmosphere: "Accretion disk fed by companion star HDE 226868",
    facts: [
      "First object widely accepted as a black hole (1972)",
      "Steals matter from companion star HDE 226868",
      "Emits X-rays powerful enough to detect from Earth",
      "Part of a 5.6-day binary orbit with a blue supergiant",
      "21 solar masses compressed into a few kilometers",
      "HDE 226868 companion: 40 solar masses, 21\u00d7 Sun's radius",
      "Subject of 1975 bet between Hawking and Kip Thorne",
      "Hawking conceded in 1990: it really is a black hole"
    ]
  },
  hde226868: {
    name: "HDE 226868",
    symbol: "\u2605",
    subtitle: "Blue Supergiant (BH Companion)",
    info: "Massive companion star being devoured by Cygnus X-1",
    distance: "7,200 light-years",
    diameter: "~21,000,000 km (21\u00d7 Sun)",
    period: "5.6 Earth days (around Cygnus X-1)",
    dayLength: "5.6 Earth days (tidally locked)",
    temperature: "30,000\u00b0C (surface)",
    gravity: "8g (surface)",
    moons: 0,
    atmosphere: "Hydrogen, helium — being stripped by black hole",
    facts: [
      "Mass donor to the Cygnus X-1 black hole",
      "Stellar wind feeds the BH accretion disk at high rate",
      "OB-type supergiant — one of the most luminous star types",
      "Tidally locked to the black hole's orbit",
      "Will itself become a black hole in a few million years",
      "Its wind hitting BH's gravity creates the X-ray emission",
      "Observable with binoculars as a faint 9th magnitude star"
    ]
  },
  // ── Supergiant Stars ──
  vyCanisMajoris: {
    name: "VY CANIS MAJORIS",
    symbol: "\u2605",
    subtitle: "Extreme Red Hypergiant",
    info: "One of the largest stars known — surface reaches Saturn's orbit",
    distance: "3,900 light-years",
    diameter: "2,800,000,000 km (1,400\u20132,000\u00d7 Sun)",
    period: "\u2014",
    dayLength: "~200 Earth days",
    temperature: "3,490\u00b0C (surface)",
    gravity: "0.0001g (surface)",
    moons: 0,
    atmosphere: "Massive stellar wind with dust clouds and OH masers",
    facts: [
      "If placed at Sun's center, surface would reach Saturn's orbit",
      "Loses mass 100\u00d7 faster than Betelgeuse via stellar wind",
      "Surrounded by dusty nebula from prior mass ejections",
      "Luminosity: 270,000 times our Sun",
      "OH (hydroxyl) maser emissions detected from ejected gas",
      "Expected to explode as a hypernova within 100,000 years",
      "One of the few stars resolvable as a disk by telescopes",
      "Extremely unstable — surface convection cells span the star"
    ]
  },
  // ── Massive Neutron Stars ──
  psrJ0348: {
    name: "PSR J0348+0432",
    symbol: "\u2726",
    subtitle: "Most Massive Neutron Star",
    info: "Record-breaking neutron star at limit of physics",
    distance: "2,100 light-years",
    diameter: "~25 km",
    period: "39 milliseconds (rotation)",
    dayLength: "25.6 rotations per second",
    temperature: "1,000,000\u00b0C (surface)",
    gravity: "200,000,000,000g (surface)",
    moons: 0,
    atmosphere: "Solid neutron matter crust 1km thick",
    facts: [
      "Most massive neutron star known: 2.01 solar masses",
      "At theoretical maximum mass limit",
      "Compresses 2 Suns into city-sized sphere",
      "White dwarf companion orbits every 2.46 hours",
      "Proves general relativity in strong gravity",
      "Will likely collapse into black hole eventually",
      "Discovered 2007 by Green Bank Telescope",
      "Density: 1 teaspoon = 5 billion tons"
    ]
  },
  psrJ0348Companion: {
    name: "PSR J0348 COMPANION",
    symbol: "\u2609",
    subtitle: "White Dwarf (Pulsar Companion)",
    info: "Compact white dwarf racing around a record-breaking pulsar",
    distance: "2,100 light-years",
    diameter: "~14,000 km (1.1\u00d7 Earth)",
    period: "2.46 hours (around PSR J0348)",
    dayLength: "2.46 hours (tidally locked)",
    temperature: "10,000\u00b0C (cooling white dwarf)",
    gravity: "100,000g (surface)",
    moons: 0,
    atmosphere: "Helium envelope (degenerate carbon-oxygen core)",
    facts: [
      "Orbits the most massive neutron star known every 2.46 hours",
      "System proves general relativity under extreme gravity",
      "Gravitational wave emission slowing the orbit measurably",
      "Both objects will eventually merge in billions of years",
      "Merger would likely form a black hole",
      "Same mass as Sun packed into Earth-sized sphere",
      "One of tightest known neutron star \u2013 white dwarf binaries"
    ]
  },
  magnetar: {
    name: "SGR 1806-20",
    symbol: "\u2726",
    subtitle: "Magnetar (Extreme Neutron Star)",
    info: "Most magnetic object in the known universe",
    distance: "42,000 light-years",
    diameter: "~20 km",
    period: "7.5 seconds (slow for neutron star)",
    dayLength: "8 rotations per minute",
    temperature: "500,000\u00b0C (surface)",
    gravity: "100,000,000,000g (surface)",
    moons: 0,
    atmosphere: "Quark-gluon plasma under magnetic field",
    facts: [
      "Magnetic field: 10^15 Gauss (quadrillion x Earth)",
      "2004 megaflare: brighter than Moon for 0.1 second",
      "Energy released: what Sun produces in 150,000 years",
      "Could wipe credit cards from Moon distance",
      "Surface starquakes crack neutron crust",
      "Slower rotation due to magnetic braking",
      "May have solid core of exotic quark matter",
      "Radio emissions prove existence of magnetars"
    ]
  },
  // ── Galaxies ──
  milkyWayGal: {
    name: "MILKY WAY",
    symbol: "\u229B",
    subtitle: "Our Home Galaxy",
    info: "Barred spiral galaxy — home to our Solar System",
    distance: "0 (we are inside it)",
    diameter: "105,700 light-years",
    period: "225 million years (galactic year)",
    dayLength: "N/A",
    temperature: "Varies from cold molecular clouds to million-degree plasma",
    gravity: "N/A (Sgr A\u2217 anchors center)",
    moons: 0,
    atmosphere: "N/A",
    facts: [
      "Contains 100\u2013400 billion stars",
      "Barred spiral galaxy with 4 major spiral arms",
      "Sagittarius A\u2217 (4.3 million solar masses) at galactic center",
      "Our Solar System orbits 26,000 light-years from center",
      "Dark matter halo extends ~300,000 light-years",
      "Andromeda Galaxy will collide with us in ~4.5 billion years",
      "Traveling at 552 km/s relative to cosmic microwave background",
      "Part of the Local Group — 54 galaxies bound by gravity"
    ]
  },
  andromedaGal: {
    name: "ANDROMEDA",
    symbol: "\u229B",
    subtitle: "Nearest Large Spiral Galaxy",
    info: "M31 — our cosmic neighbor, on a collision course with us",
    distance: "2.537 million light-years",
    diameter: "220,000 light-years",
    period: "~200 million years (galactic rotation)",
    dayLength: "N/A",
    temperature: "Varies",
    gravity: "N/A",
    moons: 0,
    atmosphere: "N/A",
    facts: [
      "Closest large galaxy to the Milky Way",
      "Contains ~1 trillion stars (2.5\u00d7 the Milky Way)",
      "Approaching at 110 km/s — collision in 4.5 billion years",
      "Merger will create 'Milkomeda', an elliptical galaxy",
      "Visible to the naked eye on dark nights as a fuzzy patch",
      "Has 2 prominent satellite galaxies: M32 and M110",
      "Edwin Hubble proved it's a separate galaxy in 1924",
      "Contains 26 known pulsars and thousands of globular clusters"
    ]
  },
  largeMagellanicCloud: {
    name: "LARGE MAGELLANIC CLOUD",
    symbol: "\u229B",
    subtitle: "Satellite Irregular Galaxy",
    info: "Closest satellite galaxy — orbiting the Milky Way",
    distance: "162,000 light-years",
    diameter: "14,000 light-years",
    period: "~1.5 billion years (orbit around Milky Way)",
    dayLength: "N/A",
    temperature: "Varies",
    gravity: "N/A",
    moons: 0,
    atmosphere: "N/A",
    facts: [
      "Closest irregular galaxy to Earth",
      "Contains the Tarantula Nebula — most active nearby star-forming region",
      "Home of R136a1 — most massive known star",
      "In gravitational orbit around the Milky Way",
      "Supernova SN 1987A was observed here in real-time",
      "Contains approximately 30 billion stars",
      "First catalogued by Ferdinand Magellan in 1519",
      "Connected to Milky Way by the Magellanic Stream gas bridge"
    ]
  },
  m87Galaxy: {
    name: "M87 GALAXY",
    symbol: "\u229B",
    subtitle: "Giant Elliptical Galaxy",
    info: "Home of M87\u2217 — first photographed black hole",
    distance: "53.5 million light-years",
    diameter: "980,000 light-years",
    period: "N/A",
    dayLength: "N/A",
    temperature: "Varies",
    gravity: "N/A",
    moons: 0,
    atmosphere: "N/A",
    facts: [
      "Giant elliptical galaxy at the heart of the Virgo Cluster",
      "Home to M87\u2217: 6.5 billion solar mass black hole",
      "Contains an estimated 1 trillion stars",
      "Ejects a 5,000 light-year plasma jet from its central BH",
      "Has over 15,000 globular clusters (Milky Way has ~150)",
      "One of the most massive galaxies in the local universe",
      "First observed by Charles Messier in 1781",
      "Dominant galaxy of the Virgo Supercluster"
    ]
  },
}

// ── Physics configuration ────────────────────────────────────────────────────
// Coordinate system: Sun at (0,0), distances in pixels
// G and masses tuned for visual stability at 1200x1200 space

export const G = 100

// Start angles derived from CSS animation-delay / duration * 2PI
// e.g. Mercury: delay=-1s, duration=6s → 1/6 * 2PI ≈ 1.047 rad
export const bodyConfig = [
  // ── Sun ──
  {
    id: 'sun',
    mass: 10000,
    radius: 40,
    orbitRadius: 0,
    parent: null,
    domSelector: '.sun',
    color: '#ffcc00',
    trailMax: 0,
    startAngle: 0,
  },
  // ── Planets ──
  {
    id: 'mercury',
    mass: 0.01,
    radius: 6,
    orbitRadius: 70,
    parent: 'sun',
    domSelector: '.mercury',
    color: '#a5a5a5',
    trailMax: 400,
    startAngle: (1 / 6) * Math.PI * 2,       // delay -1s / 6s
  },
  {
    id: 'venus',
    mass: 0.05,
    radius: 11,
    orbitRadius: 105,
    parent: 'sun',
    domSelector: '.venus',
    color: '#e3bb76',
    trailMax: 500,
    startAngle: (4 / 6.1) * Math.PI * 2,     // delay -4s / 6.1s
  },
  {
    id: 'earth',
    mass: 5,
    radius: 12.5,
    orbitRadius: 150,
    parent: 'sun',
    domSelector: '.earth',
    color: '#2b82c9',
    trailMax: 600,
    startAngle: (2 / 10) * Math.PI * 2,      // delay -2s / 10s
  },
  {
    id: 'mars',
    mass: 2,
    radius: 9,
    orbitRadius: 195,
    parent: 'sun',
    domSelector: '.mars',
    color: '#e27b58',
    trailMax: 600,
    startAngle: (5 / 18.8) * Math.PI * 2,
  },
  {
    id: 'jupiter',
    mass: 50,
    radius: 25,
    orbitRadius: 275,
    parent: 'sun',
    domSelector: '.jupiter',
    color: '#d39c7e',
    trailMax: 600,
    startAngle: (10 / 40) * Math.PI * 2,
  },
  {
    id: 'saturn',
    mass: 30,
    radius: 22.5,
    orbitRadius: 350,
    parent: 'sun',
    domSelector: '.saturn',
    color: '#c5ab6e',
    trailMax: 600,
    startAngle: (15 / 60) * Math.PI * 2,
  },
  {
    id: 'uranus',
    mass: 10,
    radius: 15,
    orbitRadius: 425,
    parent: 'sun',
    domSelector: '.uranus',
    color: '#b3d1d1',
    trailMax: 600,
    startAngle: (20 / 80) * Math.PI * 2,
  },
  {
    id: 'neptune',
    mass: 10,
    radius: 15,
    orbitRadius: 480,
    parent: 'sun',
    domSelector: '.neptune',
    color: '#6081ff',
    trailMax: 600,
    startAngle: (30 / 120) * Math.PI * 2,
  },
  {
    id: 'pluto',
    mass: 0.5,
    radius: 5,
    orbitRadius: 550,
    parent: 'sun',
    domSelector: '.pluto',
    color: '#7f7f7f',
    trailMax: 600,
    startAngle: (40 / 150) * Math.PI * 2,
  },
  // ── Moons ──
  {
    id: 'moon',
    mass: 0.001,
    radius: 3,
    orbitRadius: 22.5,
    parent: 'earth',
    domSelector: '.moon',
    color: '#dddddd',
    trailMax: 200,
    startAngle: (1 / 2.7) * Math.PI * 2,
  },
  {
    id: 'phobos',
    mass: 0.0001,
    radius: 1.5,
    orbitRadius: 15,
    parent: 'mars',
    domSelector: '.phobos',
    color: '#9d8e87',
    trailMax: 150,
    startAngle: (0.5 / 1) * Math.PI * 2,
  },
  {
    id: 'deimos',
    mass: 0.0001,
    radius: 1,
    orbitRadius: 22.5,
    parent: 'mars',
    domSelector: '.deimos',
    color: '#9d8e87',
    trailMax: 150,
    startAngle: (1.5 / 3) * Math.PI * 2,
  },
  {
    id: 'io',
    mass: 0.001,
    radius: 2,
    orbitRadius: 35,
    parent: 'jupiter',
    domSelector: '.io',
    color: '#f9e231',
    trailMax: 150,
    startAngle: (0.5 / 2) * Math.PI * 2,
  },
  {
    id: 'europa',
    mass: 0.001,
    radius: 1.75,
    orbitRadius: 45,
    parent: 'jupiter',
    domSelector: '.europa',
    color: '#fdf5e6',
    trailMax: 150,
    startAngle: (1 / 4) * Math.PI * 2,
  },
  {
    id: 'ganymede',
    mass: 0.002,
    radius: 2.5,
    orbitRadius: 57.5,
    parent: 'jupiter',
    domSelector: '.ganymede',
    color: '#95877c',
    trailMax: 150,
    startAngle: (2 / 7) * Math.PI * 2,
  },
  {
    id: 'titan',
    mass: 0.002,
    radius: 3,
    orbitRadius: 60,
    parent: 'saturn',
    domSelector: '.titan',
    color: '#e3bb76',
    trailMax: 150,
    startAngle: (3 / 10) * Math.PI * 2,
  },
  {
    id: 'titania',
    mass: 0.001,
    radius: 1.5,
    orbitRadius: 25,
    parent: 'uranus',
    domSelector: '.titania',
    color: '#dcdcdc',
    trailMax: 150,
    startAngle: (1 / 5) * Math.PI * 2,
  },
  {
    id: 'triton',
    mass: 0.001,
    radius: 2,
    orbitRadius: 30,
    parent: 'neptune',
    domSelector: '.triton',
    color: '#d2f8f8',
    trailMax: 150,
    startAngle: (1 / 6) * Math.PI * 2,
    retrograde: true,
  },
  {
    id: 'charon',
    mass: 0.001,
    radius: 1,
    orbitRadius: 10,
    parent: 'pluto',
    domSelector: '.charon',
    color: '#a5a5a5',
    trailMax: 100,
    startAngle: (0.5 / 1) * Math.PI * 2,
    retrograde: true,
  },
]

// ── Scene Configurations ──────────────────────────────────────────────────
// Each scene defines which bodies to render and their physics configs

export const scenes = {
  solar: {
    id: 'solar',
    name: 'Solar System',
    icon: '\u2609',
    description: 'Our home planetary system',
    bodyIds: ['sun', 'mercury', 'venus', 'earth', 'mars', 'jupiter', 'saturn', 'uranus', 'neptune', 'pluto',
              'moon', 'phobos', 'deimos', 'io', 'europa', 'ganymede', 'titan', 'titania', 'triton', 'charon'],
    backgroundType: 'stars',
    scale: 1,
  },
  stellar: {
    id: 'stellar',
    name: 'Stellar Remnants',
    icon: '\u2726',
    description: 'End states of massive stars',
    bodyIds: ['siriusA', 'siriusB', 'velaPulsar', 'sagittariusA'],
    backgroundType: 'nebula',
    scale: 0.8,
  },
  exoplanets: {
    id: 'exoplanets',
    name: 'TRAPPIST-1',
    icon: '\u2727',
    description: 'Ultra-cool dwarf with 7 rocky worlds',
    bodyIds: ['trappist1', 'trappist1b', 'trappist1e', 'trappist1f'],
    backgroundType: 'deep',
    scale: 1.2,
  },
  blackholes: {
    id: 'blackholes',
    name: 'Black Holes',
    icon: '\u25C9',
    description: 'Cosmic gravitational monsters',
    bodyIds: ['ton618', 'm87bh', 'cygnusX1', 'hde226868'],
    backgroundType: 'blackhole',
    scale: 1,
  },
  supergiants: {
    id: 'supergiants',
    name: 'Supergiant Stars',
    icon: '\u2605',
    description: 'Monster stars nearing supernova',
    bodyIds: ['betelgeuse', 'vyCanisMajoris', 'r136a1'],
    backgroundType: 'nebula',
    scale: 1,
  },
  neutrons: {
    id: 'neutrons',
    name: 'Neutron Stars',
    icon: '\u2299',
    description: 'City-sized remnants of supernova explosions',
    bodyIds: ['velaPulsar', 'psrJ0348', 'psrJ0348Companion', 'magnetar'],
    backgroundType: 'deep',
    scale: 1,
  },
  galaxies: {
    id: 'galaxies',
    name: 'Galaxies',
    icon: '\u229B',
    description: 'Island universes across the cosmos',
    bodyIds: ['milkyWayGal', 'andromedaGal', 'largeMagellanicCloud', 'm87Galaxy'],
    backgroundType: 'galaxy',
    scale: 1,
  },
}

// ── Scene-specific body configurations ─────────────────────────────────────
// Bodies not in solar system need special configs

export const sceneBodyConfigs = {
  // Stellar Remnants scene bodies
  siriusA: {
    id: 'siriusA',
    mass: 20000,
    radius: 45,
    orbitRadius: 0,
    parent: null,
    startX: -160,
    startY: 20,
    domSelector: '.sirius-a',
    color: '#aaccff',
    trailMax: 0,
    sceneType: 'stellar',
  },
  siriusB: {
    id: 'siriusB',
    mass: 0.01,
    radius: 8,
    orbitRadius: 120,
    parent: 'siriusA',
    domSelector: '.sirius-b',
    color: '#ffffff',
    trailMax: 400,
    startAngle: 0,
    sceneType: 'stellar',
  },
  velaPulsar: {
    id: 'velaPulsar',
    mass: 0,
    radius: 12,
    orbitRadius: 0,
    parent: null,
    startX: 20,
    startY: -200,
    domSelector: '.vela-pulsar',
    color: '#44aaff',
    trailMax: 0,
    pulseEffect: true,
    sceneType: 'stellar',
  },
  sagittariusA: {
    id: 'sagittariusA',
    mass: 0,
    radius: 60,
    orbitRadius: 0,
    parent: null,
    startX: 210,
    startY: 150,
    domSelector: '.sagittarius-a',
    color: '#000000',
    trailMax: 0,
    accretionDisk: true,
    sceneType: 'stellar',
  },
  // TRAPPIST-1 system bodies
  trappist1: {
    id: 'trappist1',
    mass: 800,
    radius: 25,
    orbitRadius: 0,
    parent: null,
    domSelector: '.trappist-1',
    color: '#ff6644',
    trailMax: 0,
    startAngle: 0,
    glowEffect: true,
    sceneType: 'exoplanets',
  },
  trappist1b: {
    id: 'trappist1b',
    mass: 0.8,
    radius: 9,
    orbitRadius: 50,
    parent: 'trappist1',
    domSelector: '.trappist-1b',
    color: '#cc8866',
    trailMax: 300,
    startAngle: 0,
    sceneType: 'exoplanets',
  },
  trappist1e: {
    id: 'trappist1e',
    mass: 0.7,
    radius: 7.5,
    orbitRadius: 85,
    parent: 'trappist1',
    domSelector: '.trappist-1e',
    color: '#66aa88',
    trailMax: 350,
    startAngle: Math.PI,
    sceneType: 'exoplanets',
  },
  trappist1f: {
    id: 'trappist1f',
    mass: 0.9,
    radius: 8.5,
    orbitRadius: 115,
    parent: 'trappist1',
    domSelector: '.trappist-1f',
    color: '#6688cc',
    trailMax: 400,
    startAngle: Math.PI * 1.5,
    sceneType: 'exoplanets',
  },

  // ── Black Holes scene ─────────────────────────────────────────────────────
  ton618: {
    id: 'ton618',
    mass: 0,
    radius: 90,
    orbitRadius: 0,
    parent: null,
    startX: 0,
    startY: 0,
    domSelector: '.ton-618',
    color: '#ff6600',
    trailMax: 0,
    accretionDisk: true,
    sceneType: 'blackholes',
  },
  m87bh: {
    id: 'm87bh',
    mass: 0,
    radius: 60,
    orbitRadius: 0,
    parent: null,
    startX: 270,
    startY: -110,
    domSelector: '.m87-bh',
    color: '#ff8800',
    trailMax: 0,
    accretionDisk: true,
    sceneType: 'blackholes',
  },
  cygnusX1: {
    id: 'cygnusX1',
    mass: 50000,
    radius: 22,
    orbitRadius: 0,
    parent: null,
    startX: -230,
    startY: 140,
    domSelector: '.cygnus-x1',
    color: '#cc4400',
    trailMax: 0,
    accretionDisk: true,
    sceneType: 'blackholes',
  },
  hde226868: {
    id: 'hde226868',
    mass: 0.01,
    radius: 20,
    orbitRadius: 80,
    parent: 'cygnusX1',
    startAngle: Math.PI / 3,
    domSelector: '.hde-226868',
    color: '#aaccff',
    trailMax: 350,
    sceneType: 'blackholes',
  },

  // ── Supergiant Stars scene ────────────────────────────────────────────────
  betelgeuse: {
    id: 'betelgeuse',
    mass: 0,
    radius: 100,
    orbitRadius: 0,
    parent: null,
    startX: 80,
    startY: 30,
    domSelector: '.betelgeuse',
    color: '#ff4400',
    trailMax: 0,
    glowEffect: true,
    sceneType: 'supergiants',
  },
  vyCanisMajoris: {
    id: 'vyCanisMajoris',
    mass: 0,
    radius: 130,
    orbitRadius: 0,
    parent: null,
    startX: -270,
    startY: 60,
    domSelector: '.vy-canis-majoris',
    color: '#cc2200',
    trailMax: 0,
    glowEffect: true,
    sceneType: 'supergiants',
  },
  r136a1: {
    id: 'r136a1',
    mass: 0,
    radius: 50,
    orbitRadius: 0,
    parent: null,
    startX: 260,
    startY: -110,
    domSelector: '.r136a1',
    color: '#aaccff',
    trailMax: 0,
    glowEffect: true,
    sceneType: 'supergiants',
  },

  // ── Neutron Stars scene ───────────────────────────────────────────────────
  psrJ0348: {
    id: 'psrJ0348',
    mass: 20000,
    radius: 14,
    orbitRadius: 0,
    parent: null,
    startX: -180,
    startY: 100,
    domSelector: '.psr-j0348',
    color: '#66aaff',
    trailMax: 0,
    pulseEffect: true,
    sceneType: 'neutrons',
  },
  psrJ0348Companion: {
    id: 'psrJ0348Companion',
    mass: 0.01,
    radius: 7,
    orbitRadius: 55,
    parent: 'psrJ0348',
    startAngle: Math.PI / 4,
    domSelector: '.psr-j0348-companion',
    color: '#e8e8ff',
    trailMax: 300,
    sceneType: 'neutrons',
  },
  magnetar: {
    id: 'magnetar',
    mass: 0,
    radius: 14,
    orbitRadius: 0,
    parent: null,
    startX: 200,
    startY: 100,
    domSelector: '.magnetar',
    color: '#cc44ff',
    trailMax: 0,
    pulseEffect: true,
    sceneType: 'neutrons',
  },

  // ── Galaxies scene ────────────────────────────────────────────────────────
  milkyWayGal: {
    id: 'milkyWayGal',
    mass: 0,
    radius: 100,
    orbitRadius: 0,
    parent: null,
    startX: 30,
    startY: 30,
    domSelector: '.milky-way',
    color: '#ffe8b0',
    trailMax: 0,
    sceneType: 'galaxies',
  },
  andromedaGal: {
    id: 'andromedaGal',
    mass: 0,
    radius: 120,
    orbitRadius: 0,
    parent: null,
    startX: 290,
    startY: -100,
    domSelector: '.andromeda',
    color: '#c8d8ff',
    trailMax: 0,
    sceneType: 'galaxies',
  },
  largeMagellanicCloud: {
    id: 'largeMagellanicCloud',
    mass: 0,
    radius: 60,
    orbitRadius: 0,
    parent: null,
    startX: -200,
    startY: 200,
    domSelector: '.large-magellanic-cloud',
    color: '#d8e8ff',
    trailMax: 0,
    sceneType: 'galaxies',
  },
  m87Galaxy: {
    id: 'm87Galaxy',
    mass: 0,
    radius: 80,
    orbitRadius: 0,
    parent: null,
    startX: -270,
    startY: -150,
    domSelector: '.m87-galaxy',
    color: '#ffcc88',
    trailMax: 0,
    sceneType: 'galaxies',
  },
}
