// ── Display data (preserved from original planetData) ────────────────────────
export const planetData = {
  sun: {
    name: "SUN",
    symbol: "\u2609",
    subtitle: "Yellow Dwarf Star",
    info: "The heart of our solar system",
    distance: "0",
    diameter: "1,392,000 km",
    period: "\u2014",
    dayLength: "25 Earth days",
    temperature: "5,500\u00b0C (surface)",
    gravity: "28g",
    moons: 0,
    atmosphere: "Hydrogen, Helium",
    facts: [
      "Contains 99.8% of system's mass",
      "Powers all life on Earth",
      "Nuclear fusion reactor at core"
    ]
  },
  "asteroid-belt": {
    name: "ASTEROID BELT",
    symbol: "\u2604",
    subtitle: "Main Belt Region",
    info: "Rocky debris field between Mars and Jupiter",
    distance: "329-478 million km",
    diameter: "~150 million km wide",
    period: "3-6 Earth years (varies)",
    dayLength: "N/A",
    temperature: "-73\u00b0C to -108\u00b0C",
    gravity: "Near zero (individual asteroids)",
    moons: 0,
    atmosphere: "None",
    facts: [
      "Formed from failed planet formation",
      "Jupiter's gravity prevented coalescence",
      "Ceres contains 25% of belt's total mass",
      "Safe for spacecraft (sparse distribution)",
      "Total mass: ~3% of Moon's mass",
      "Over 1.3 million cataloged asteroids"
    ]
  },
  mercury: {
    name: "MERCURY",
    symbol: "\u263f",
    subtitle: "The Swift Planet",
    info: "Smallest planet in solar system",
    distance: "57.9 million km",
    diameter: "4,879 km",
    period: "88 Earth days",
    dayLength: "59 Earth days",
    temperature: "-173\u00b0C to 427\u00b0C",
    gravity: "0.38g",
    moons: 0,
    atmosphere: "None",
    facts: [
      "Fastest orbit around Sun",
      "Extreme temperature swings",
      "Named after Roman messenger god"
    ]
  },
  venus: {
    name: "VENUS",
    symbol: "\u2640",
    subtitle: "Earth's Evil Twin",
    info: "Hottest planet in solar system",
    distance: "108.2 million km",
    diameter: "12,104 km",
    period: "225 Earth days",
    dayLength: "243 Earth days (retrograde)",
    temperature: "462\u00b0C (average)",
    gravity: "0.90g",
    moons: 0,
    atmosphere: "CO\u2082, Sulfuric Acid clouds",
    facts: [
      "Rotates backwards (retrograde)",
      "Day longer than year",
      "Volcanic hellscape"
    ]
  },
  earth: {
    name: "EARTH",
    symbol: "\ud83d\udea8",
    subtitle: "The Blue Planet",
    info: "Our home in the cosmos",
    distance: "149.6 million km",
    diameter: "12,742 km",
    period: "365.25 days",
    dayLength: "24 hours",
    temperature: "-88\u00b0C to 58\u00b0C",
    gravity: "1.0g",
    moons: 1,
    atmosphere: "N\u2082, O\u2082",
    facts: [
      "Only known planet with life",
      "71% covered by water",
      "Perfect conditions for civilization"
    ]
  },
  mars: {
    name: "MARS",
    symbol: "\u2642",
    subtitle: "The Red Planet",
    info: "Future human colony",
    distance: "227.9 million km",
    diameter: "6,779 km",
    period: "687 Earth days",
    dayLength: "24.6 hours",
    temperature: "-140\u00b0C to 20\u00b0C",
    gravity: "0.38g",
    moons: 2,
    atmosphere: "CO\u2082 (thin)",
    facts: [
      "Home to Olympus Mons (tallest mountain)",
      "Ancient riverbeds discovered",
      "Target for human colonization"
    ]
  },
  jupiter: {
    name: "JUPITER",
    symbol: "\u2643",
    subtitle: "King of Planets",
    info: "Largest planet in solar system",
    distance: "778.5 million km",
    diameter: "139,820 km",
    period: "11.9 Earth years (4,333 days)",
    dayLength: "10 hours",
    temperature: "-145\u00b0C (cloud tops)",
    gravity: "2.5g",
    moons: 79,
    atmosphere: "H\u2082, He",
    facts: [
      "Great Red Spot storm (300+ years old)",
      "Protects Earth from asteroids",
      "Could contain 1,300 Earths"
    ]
  },
  saturn: {
    name: "SATURN",
    symbol: "\u2644",
    subtitle: "Lord of the Rings",
    info: "Most spectacular ring system",
    distance: "1.4 billion km",
    diameter: "116,460 km",
    period: "29.5 Earth years (10,759 days)",
    dayLength: "10.7 hours",
    temperature: "-178\u00b0C",
    gravity: "1.1g",
    moons: 82,
    atmosphere: "H\u2082, He",
    facts: [
      "Rings made of ice and rock",
      "Low density (would float on water)",
      "Hexagonal storm at north pole"
    ]
  },
  uranus: {
    name: "URANUS",
    symbol: "\u2645",
    subtitle: "The Sideways Planet",
    info: "Ice giant with extreme tilt",
    distance: "2.9 billion km",
    diameter: "50,724 km",
    period: "84 Earth years (30,687 days)",
    dayLength: "17.2 hours (retrograde)",
    temperature: "-224\u00b0C",
    gravity: "0.89g",
    moons: 27,
    atmosphere: "H\u2082, He, CH\u2084",
    facts: [
      "Rotates on its side (98\u00b0 tilt)",
      "Faint ring system",
      "Methane gives blue-green color"
    ]
  },
  neptune: {
    name: "NEPTUNE",
    symbol: "\u2646",
    subtitle: "The Windy World",
    info: "Fastest winds in solar system",
    distance: "4.5 billion km",
    diameter: "49,244 km",
    period: "165 Earth years (60,190 days)",
    dayLength: "16 hours",
    temperature: "-214\u00b0C",
    gravity: "1.1g",
    moons: 14,
    atmosphere: "H\u2082, He, CH\u2084",
    facts: [
      "Winds reach 2,100 km/h",
      "Dark Spot storms",
      "Discovered by mathematics"
    ]
  },
  pluto: {
    name: "PLUTO",
    symbol: "\u2647",
    subtitle: "The Heart of Ice",
    info: "Dwarf planet in Kuiper Belt",
    distance: "5.9 billion km",
    diameter: "2,377 km",
    period: "248 Earth years (90,560 days)",
    dayLength: "6.4 Earth days",
    temperature: "-229\u00b0C",
    gravity: "0.06g",
    moons: 5,
    atmosphere: "N\u2082, CH\u2084 (seasonal)",
    facts: [
      "Heart-shaped ice plain (Tombaugh Regio)",
      "Reclassified as dwarf planet (2006)",
      "Five moons in complex dance"
    ]
  },
  // ── Stellar Remnants ──
  siriusA: {
    name: "SIRIUS A",
    symbol: "\u2609",
    subtitle: "Brightest Star in Night Sky",
    info: "A-type main sequence star, 25x brighter than Sun",
    distance: "8.6 light-years",
    diameter: "2,400,000 km (1.7x Sun)",
    period: "\u2014",
    dayLength: "~5 Earth days",
    temperature: "9,940\u00b0C (surface)",
    gravity: "4.3g (surface)",
    moons: 0,
    atmosphere: "Hydrogen, helium (fusion core)",
    facts: [
      "Brightest star visible from Earth",
      "Called 'Dog Star' - part of Canis Major",
      "Only 2x Sun's mass but 25x brighter",
      "Will become red giant in ~1 billion years",
      "Sirius B orbits it every 50 years",
      "Rises with Sun in summer (dog days)",
      "Visible from almost entire Earth"
    ]
  },
  siriusB: {
    name: "SIRIUS B",
    symbol: "\u2609",
    subtitle: "White Dwarf Star",
    info: "Earth-sized star with solar mass, companion to Sirius A",
    distance: "8.6 light-years",
    diameter: "11,684 km (0.84x Earth)",
    period: "50.1 years (binary orbit)",
    dayLength: "Unknown (rotating)",
    temperature: "25,200\u00b0C (surface)",
    gravity: "350,000g (surface)",
    moons: 0,
    atmosphere: "Carbon/oxygen core, helium envelope",
    facts: [
      "Most massive white dwarf known: 0.98 solar masses",
      "Same size as Earth but mass of our Sun",
      "Discovered 1862 by Alvan Clark",
      "Will cool into black dwarf over trillions of years",
      "Was a main-sequence star 120 million years ago",
      "Companion Sirius A is brightest star in night sky"
    ]
  },
  velaPulsar: {
    name: "VELA PULSAR",
    symbol: "\u2726",
    subtitle: "Neutron Star (Pulsar)",
    info: "Rotating neutron star emitting beams of radiation",
    distance: "936 light-years",
    diameter: "~20 km (city-sized)",
    period: "89.3 milliseconds (rotation)",
    dayLength: "11 rotations per second",
    temperature: "1,000,000\u00b0C (surface)",
    gravity: "100,000,000,000g (surface)",
    moons: 0,
    atmosphere: "None (pure neutron matter crust)",
    facts: [
      "Spins 11 times per second, emitting lighthouse beams",
      "Supernova remnant from 11,000 years ago",
      "One sugar-cube of matter weighs 1 billion tons",
      "Magnetic field 1 trillion times stronger than Earth's",
      "Visible to naked eye in very dark skies",
      "Proves prediction of neutron stars (1934 Landau)",
      "Part of Vela Supernova Remnant in southern sky"
    ]
  },
  sagittariusA: {
    name: "SAGITTARIUS A*",
    symbol: "\u2605",
    subtitle: "Supermassive Black Hole",
    info: "4 million solar mass monster at Milky Way's center",
    distance: "26,673 light-years",
    diameter: "51.8 million km (event horizon)",
    period: "Rotation ~10 minutes (near light speed)",
    dayLength: "Inapplicable (frozen time at horizon)",
    temperature: "Absolute zero (hawking radiation ~10^-7 K)",
    gravity: "Infinite at singularity",
    moons: 0,
    atmosphere: "Accretion disk of superheated plasma",
    facts: [
      "First black hole imaged by EHT in 2022",
      "4.3 million times the mass of our Sun",
      "Event horizon diameter equals Mercury's orbit",
      "Surrounded by hot gas swirling at 30% light speed",
      "S-stars orbit it at 3% light speed",
      "Discovered via radio emissions in 1974",
      "Accretion disk glows at millions of degrees",
      "Controls rotation of entire Milky Way galaxy"
    ]
  },
  // ── TRAPPIST-1 Exoplanet System ──
  trappist1: {
    name: "TRAPPIST-1",
    symbol: "\u2609",
    subtitle: "Ultra-Cool Red Dwarf Star",
    info: "Host star to 7 Earth-sized rocky planets",
    distance: "39 light-years",
    diameter: "160,000 km (0.12x Sun)",
    period: "\u2014",
    dayLength: "3.3 Earth days",
    temperature: "2,566\u00b0C (surface)",
    gravity: "0.08g (surface)",
    moons: 0,
    atmosphere: "Hydrogen (red dwarf)",
    facts: [
      "Discovered 2010 by TRAPPIST telescope in Chile",
      "Planets discovered 2015-2017 by Spitzer Space Telescope",
      "All 7 planets could potentially have liquid water",
      "3 planets in habitable zone (b, c, d)",
      "Star is barely larger than Jupiter",
      "Planets are gravitationally locked (tidally)",
      "Perfect target for JWST atmospheric studies",
      "Most studied planetary system beyond our own"
    ]
  },
  trappist1b: {
    name: "TRAPPIST-1b",
    symbol: "b",
    subtitle: "Rocky Exoplanet",
    info: "Hot world 100x closer to star than Earth",
    distance: "1.5 million km from TRAPPIST-1",
    diameter: "11,553 km (0.9x Earth)",
    period: "1.5 Earth days",
    dayLength: "Tidally locked (1.5 days)",
    temperature: "~400\u00b0C (dayside)",
    gravity: "0.85g",
    moons: 0,
    atmosphere: "Likely lost to stellar wind",
    facts: [
      "Too hot for liquid water, likely Venus-like",
      "Tidally locked: one side always faces star",
      "Orbit period just 36 hours",
      " receives 4x more radiation than Mercury",
      "JWST detected no significant atmosphere",
      "Surface may be volcanic or desert",
      "Innermost of 7 known planets"
    ]
  },
  trappist1e: {
    name: "TRAPPIST-1e",
    symbol: "e",
    subtitle: "Potentially Habitable Exoplanet",
    info: "Best candidate for habitability in the system",
    distance: "4.3 million km from TRAPPIST-1",
    diameter: "9,140 km (0.72x Earth)",
    period: "6.1 Earth days",
    dayLength: "Tidally locked (6.1 days)",
    temperature: "-20\u00b0C to 40\u00b0C (estimated)",
    gravity: "0.93g",
    moons: 0,
    atmosphere: "Unknown (under study by JWST)",
    facts: [
      "Most similar to Earth in radiation received",
      "Rocky world slightly smaller than Earth",
      "In habitable zone where water could be liquid",
      "May have thin atmosphere like Mars",
      "JWST searching for CO2, water vapor, methane",
      "Twilight zone could be most habitable",
      "Future target for direct imaging",
      "Could have subsurface oceans"
    ]
  },
  trappist1c: {
    name: "TRAPPIST-1c",
    symbol: "c",
    subtitle: "Rocky Venus-like Exoplanet",
    info: "Hot rocky world \u2014 similar size to Earth, likely Venus-like",
    distance: "2.3 million km from TRAPPIST-1",
    diameter: "11,100 km (0.87x Earth)",
    period: "2.42 Earth days",
    dayLength: "Tidally locked (2.42 days)",
    temperature: "~320\u00b0C (dayside estimate)",
    gravity: "1.04g",
    moons: 0,
    atmosphere: "Likely thin or none (stripped by stellar wind)",
    facts: [
      "Second planet from TRAPPIST-1, just outside planet b",
      "JWST measured very low thermal emission in 2023",
      "Results suggest a bare rock with no significant atmosphere",
      "If there is atmosphere, it's thin CO2 at most",
      "Nearly Earth-sized but too hot for liquid water",
      "Receives ~2.25x the solar radiation Earth gets",
      "Tidally locked \u2014 permanent day and night sides",
      "Key calibration target for rocky exoplanet atmospheres"
    ]
  },
  trappist1d: {
    name: "TRAPPIST-1d",
    symbol: "d",
    subtitle: "Smallest TRAPPIST Planet",
    info: "Lightest world in the system \u2014 may be dry rocky or ocean world",
    distance: "3.2 million km from TRAPPIST-1",
    diameter: "7,980 km (0.79x Earth)",
    period: "4.05 Earth days",
    dayLength: "Tidally locked (4.05 days)",
    temperature: "~60\u00b0C (dayside estimate)",
    gravity: "0.67g",
    moons: 0,
    atmosphere: "Unknown \u2014 JWST study ongoing",
    facts: [
      "Smallest and least massive of the 7 TRAPPIST-1 planets",
      "Just inside the inner edge of the optimistic habitable zone",
      "Receives ~1.14x Earth's solar radiation",
      "Could support liquid water with a thick atmosphere",
      "Density suggests rocky composition with possible water",
      "Low gravity means atmosphere is harder to retain",
      "Transit timing variations reveal gravitational interaction with neighbors",
      "Prime target for JWST to search for atmospheric signatures"
    ]
  },
  trappist1f: {
    name: "TRAPPIST-1f",
    symbol: "f",
    subtitle: "Water World Candidate",
    info: "Likely global ocean or thick ice shell",
    distance: "5.7 million km from TRAPPIST-1",
    diameter: "10,400 km (0.82x Earth)",
    period: "9.2 Earth days",
    dayLength: "Tidally locked (9.2 days)",
    temperature: "-50\u00b0C to 0\u00b0C (estimated)",
    gravity: "0.68g",
    moons: 0,
    atmosphere: "Unknown (possibly thick CO2)",
    facts: [
      "Likely covered in global ocean or ice",
      "Could have 20x Earth's water content",
      "Just outside inner edge of habitable zone",
      "May be 'eyeball planet' with ice and water",
      "Thick atmosphere possible for heat retention",
      "Rocky core under deep water layer",
      "Potential subsurface ocean habitat",
      "Best candidate for water detection"
    ]
  },
  trappist1g: {
    name: "TRAPPIST-1g",
    symbol: "g",
    subtitle: "Large Outer Rocky World",
    info: "Second largest planet \u2014 outer habitable zone edge",
    distance: "6.9 million km from TRAPPIST-1",
    diameter: "11,630 km (0.91x Earth)",
    period: "12.35 Earth days",
    dayLength: "Tidally locked (12.35 days)",
    temperature: "-100\u00b0C to -40\u00b0C (estimated)",
    gravity: "0.72g",
    moons: 0,
    atmosphere: "Unknown (possible thick H2 or CO2 greenhouse)",
    facts: [
      "Largest planet in the TRAPPIST-1 system by radius",
      "Sits just beyond the outer edge of the habitable zone",
      "Could be habitable with a strong greenhouse atmosphere",
      "Density lower than Earth's \u2014 may contain more water or volatiles",
      "Gravitational resonance chain: orbital periods are near-integer ratios",
      "Receives only 0.38x the radiation Earth gets from Sun",
      "May be an ice-covered world with subsurface liquid ocean",
      "JWST atmospheric study planned for mid-2020s"
    ]
  },
  trappist1h: {
    name: "TRAPPIST-1h",
    symbol: "h",
    subtitle: "Outermost Icy World",
    info: "Coldest, outermost TRAPPIST planet \u2014 likely a frozen world",
    distance: "9.1 million km from TRAPPIST-1",
    diameter: "7,830 km (0.77x Earth)",
    period: "18.77 Earth days",
    dayLength: "Tidally locked (18.77 days)",
    temperature: "~-220\u00b0C (estimated surface)",
    gravity: "0.56g",
    moons: 0,
    atmosphere: "Likely none \u2014 too cold and low gravity to retain gas",
    facts: [
      "Outermost of the 7 known TRAPPIST-1 planets",
      "Receives only 0.13x the radiation Earth receives from Sun",
      "Surface likely covered in thick permanent ice",
      "Discovered last, predicted by resonance chain model",
      "Orbital period ratio with planet g is approximately 3:2",
      "All 7 planets orbit closer to star than Mercury orbits our Sun",
      "May have a subsurface ocean heated by tidal forces",
      "Smallest planet in the system alongside planet d"
    ]
  },
  // ── Massive Stars & Supergiants ──
  betelgeuse: {
    name: "BETELGEUSE",
    symbol: "\u2605",
    subtitle: "Red Supergiant Star",
    info: "Monster star 700x larger than our Sun, nearing supernova",
    distance: "642.5 light-years",
    diameter: "1,234,000,000 km (887x Sun, 9.5 AU)",
    period: "\u2014",
    dayLength: "~1000 Earth days (very slow rotation)",
    temperature: "3,500\u00b0C (surface)",
    gravity: "0.0005g (surface)",
    moons: 0,
    atmosphere: "Extended stellar envelope of gas",
    facts: [
      "If placed at Sun's center, surface would reach Jupiter",
      "Expected to explode as supernova within 100,000 years",
      "Mass ~20x Sun but 700x larger radius",
      "2019 'Great Dimming' was dust cloud ejection",
      "Visible as red star in Orion constellation",
      "One of largest stars visible to naked eye",
      "Surface would extend past asteroid belt",
      "Fusion produces heavy elements: carbon to iron"
    ]
  },
  r136a1: {
    name: "R136a1",
    symbol: "\u2605",
    subtitle: "Most Massive Known Star",
    info: "Wolf-Rayet star 196x more massive than our Sun",
    distance: "163,000 light-years (Large Magellanic Cloud)",
    diameter: "~10,000,000 km (14x Sun)",
    period: "\u2014",
    dayLength: "~6 Earth days",
    temperature: "53,000\u00b0C (surface)",
    gravity: "~10g (surface)",
    moons: 0,
    atmosphere: "Extreme stellar wind stripping outer layers",
    facts: [
      "Most massive known star: 196 solar masses",
      "Brightness: 4.6 million times our Sun",
      "Will become black hole in ~2 million years",
      "Located in Tarantula Nebula outside Milky Way",
      "Strong stellar winds at 3,000 km/s",
      "Likely formed by stellar merger",
      "Hundreds of times more massive than 'normal' stars",
      "Will produce hypernova explosion, brightest in universe"
    ]
  },
  // ── Black Holes ──
  ton618: {
    name: "TON 618",
    symbol: "\u25C9",
    subtitle: "Hypermassive Quasar Black Hole",
    info: "66 billion solar masses — one of the universe's most massive black holes",
    distance: "10.4 billion light-years",
    diameter: "390 billion km (event horizon)",
    period: "Inapplicable (frozen at horizon)",
    dayLength: "Inapplicable",
    temperature: "~10\u00b9\u00b2 K (accretion disk)",
    gravity: "Infinite at singularity",
    moons: 0,
    atmosphere: "Superheated quasar jet plasma",
    facts: [
      "66 billion solar masses — among universe's most massive BHs",
      "Luminosity: 4\u00d710\u00b3\u2079 watts — 140 trillion times the Sun",
      "Event horizon: 1,300\u00d7 the Earth-Sun distance",
      "Powers a quasar brighter than entire galaxies",
      "Light from it took 10.4 billion years to reach us",
      "Formed when the universe was only 3 billion years old",
      "Would take light 190 days to cross its event horizon",
      "Located in galaxy CVn I dwarf at redshift z=2.219"
    ]
  },
  m87bh: {
    name: "M87\u2217",
    symbol: "\u25C9",
    subtitle: "First Photographed Black Hole",
    info: "6.5 billion solar mass giant at M87 galaxy's center",
    distance: "53.5 million light-years",
    diameter: "38 billion km (event horizon)",
    period: "~2 years (inner accretion orbit)",
    dayLength: "Inapplicable",
    temperature: "~10\u00b9\u00b2 K (accretion disk)",
    gravity: "Infinite at singularity",
    moons: 0,
    atmosphere: "Relativistic jet extending 5,000 light-years",
    facts: [
      "First black hole ever directly imaged — April 10, 2019",
      "Event Horizon Telescope array photographed its shadow",
      "6.5 billion solar masses — 1,600\u00d7 Sagittarius A\u2217",
      "Ejects a relativistic plasma jet 5,000 light-years long",
      "Jet plasma travels at 99% the speed of light",
      "Located in elliptical galaxy M87 in Virgo constellation",
      "Ring image: glowing superheated plasma swirling in",
      "Shadow diameter is 2.5\u00d7 larger than Pluto's orbit around Sun"
    ]
  },
  cygnusX1: {
    name: "CYGNUS X-1",
    symbol: "\u25C9",
    subtitle: "Stellar-Mass Black Hole",
    info: "First confirmed black hole — 21 solar masses in binary system",
    distance: "7,200 light-years",
    diameter: "~350 km (Schwarzschild radius)",
    period: "5.6 Earth days (binary orbit)",
    dayLength: "Inapplicable",
    temperature: ">10\u2077 K (accretion disk)",
    gravity: "Infinite at singularity",
    moons: 0,
    atmosphere: "Accretion disk fed by companion star HDE 226868",
    facts: [
      "First object widely accepted as a black hole (1972)",
      "Steals matter from companion star HDE 226868",
      "Emits X-rays powerful enough to detect from Earth",
      "Part of a 5.6-day binary orbit with a blue supergiant",
      "21 solar masses compressed into a few kilometers",
      "HDE 226868 companion: 40 solar masses, 21\u00d7 Sun's radius",
      "Subject of 1975 bet between Hawking and Kip Thorne",
      "Hawking conceded in 1990: it really is a black hole"
    ]
  },
  hde226868: {
    name: "HDE 226868",
    symbol: "\u2605",
    subtitle: "Blue Supergiant (BH Companion)",
    info: "Massive companion star being devoured by Cygnus X-1",
    distance: "7,200 light-years",
    diameter: "~21,000,000 km (21\u00d7 Sun)",
    period: "5.6 Earth days (around Cygnus X-1)",
    dayLength: "5.6 Earth days (tidally locked)",
    temperature: "30,000\u00b0C (surface)",
    gravity: "8g (surface)",
    moons: 0,
    atmosphere: "Hydrogen, helium — being stripped by black hole",
    facts: [
      "Mass donor to the Cygnus X-1 black hole",
      "Stellar wind feeds the BH accretion disk at high rate",
      "OB-type supergiant — one of the most luminous star types",
      "Tidally locked to the black hole's orbit",
      "Will itself become a black hole in a few million years",
      "Its wind hitting BH's gravity creates the X-ray emission",
      "Observable with binoculars as a faint 9th magnitude star"
    ]
  },
  // ── Supergiant Stars ──
  vyCanisMajoris: {
    name: "VY CANIS MAJORIS",
    symbol: "\u2605",
    subtitle: "Extreme Red Hypergiant",
    info: "One of the largest stars known — surface reaches Saturn's orbit",
    distance: "3,900 light-years",
    diameter: "2,800,000,000 km (1,400\u20132,000\u00d7 Sun)",
    period: "\u2014",
    dayLength: "~200 Earth days",
    temperature: "3,490\u00b0C (surface)",
    gravity: "0.0001g (surface)",
    moons: 0,
    atmosphere: "Massive stellar wind with dust clouds and OH masers",
    facts: [
      "If placed at Sun's center, surface would reach Saturn's orbit",
      "Loses mass 100\u00d7 faster than Betelgeuse via stellar wind",
      "Surrounded by dusty nebula from prior mass ejections",
      "Luminosity: 270,000 times our Sun",
      "OH (hydroxyl) maser emissions detected from ejected gas",
      "Expected to explode as a hypernova within 100,000 years",
      "One of the few stars resolvable as a disk by telescopes",
      "Extremely unstable — surface convection cells span the star"
    ]
  },
  // ── Massive Neutron Stars ──
  psrJ0348: {
    name: "PSR J0348+0432",
    symbol: "\u2726",
    subtitle: "Most Massive Neutron Star",
    info: "Record-breaking neutron star at limit of physics",
    distance: "2,100 light-years",
    diameter: "~25 km",
    period: "39 milliseconds (rotation)",
    dayLength: "25.6 rotations per second",
    temperature: "1,000,000\u00b0C (surface)",
    gravity: "200,000,000,000g (surface)",
    moons: 0,
    atmosphere: "Solid neutron matter crust 1km thick",
    facts: [
      "Most massive neutron star known: 2.01 solar masses",
      "At theoretical maximum mass limit",
      "Compresses 2 Suns into city-sized sphere",
      "White dwarf companion orbits every 2.46 hours",
      "Proves general relativity in strong gravity",
      "Will likely collapse into black hole eventually",
      "Discovered 2007 by Green Bank Telescope",
      "Density: 1 teaspoon = 5 billion tons"
    ]
  },
  psrJ0348Companion: {
    name: "PSR J0348 COMPANION",
    symbol: "\u2609",
    subtitle: "White Dwarf (Pulsar Companion)",
    info: "Compact white dwarf racing around a record-breaking pulsar",
    distance: "2,100 light-years",
    diameter: "~14,000 km (1.1\u00d7 Earth)",
    period: "2.46 hours (around PSR J0348)",
    dayLength: "2.46 hours (tidally locked)",
    temperature: "10,000\u00b0C (cooling white dwarf)",
    gravity: "100,000g (surface)",
    moons: 0,
    atmosphere: "Helium envelope (degenerate carbon-oxygen core)",
    facts: [
      "Orbits the most massive neutron star known every 2.46 hours",
      "System proves general relativity under extreme gravity",
      "Gravitational wave emission slowing the orbit measurably",
      "Both objects will eventually merge in billions of years",
      "Merger would likely form a black hole",
      "Same mass as Sun packed into Earth-sized sphere",
      "One of tightest known neutron star \u2013 white dwarf binaries"
    ]
  },
  magnetar: {
    name: "SGR 1806-20",
    symbol: "\u2726",
    subtitle: "Magnetar (Extreme Neutron Star)",
    info: "Most magnetic object in the known universe",
    distance: "42,000 light-years",
    diameter: "~20 km",
    period: "7.5 seconds (slow for neutron star)",
    dayLength: "8 rotations per minute",
    temperature: "500,000\u00b0C (surface)",
    gravity: "100,000,000,000g (surface)",
    moons: 0,
    atmosphere: "Quark-gluon plasma under magnetic field",
    facts: [
      "Magnetic field: 10^15 Gauss (quadrillion x Earth)",
      "2004 megaflare: brighter than Moon for 0.1 second",
      "Energy released: what Sun produces in 150,000 years",
      "Could wipe credit cards from Moon distance",
      "Surface starquakes crack neutron crust",
      "Slower rotation due to magnetic braking",
      "May have solid core of exotic quark matter",
      "Radio emissions prove existence of magnetars"
    ]
  },
  // ── Galaxies ──
  milkyWayGal: {
    name: "MILKY WAY",
    symbol: "\u229B",
    subtitle: "Our Home Galaxy",
    info: "Barred spiral galaxy — home to our Solar System",
    distance: "0 (we are inside it)",
    diameter: "105,700 light-years",
    period: "225 million years (galactic year)",
    dayLength: "N/A",
    temperature: "Varies from cold molecular clouds to million-degree plasma",
    gravity: "N/A (Sgr A\u2217 anchors center)",
    moons: 0,
    atmosphere: "N/A",
    facts: [
      "Contains 100\u2013400 billion stars",
      "Barred spiral galaxy with 4 major spiral arms",
      "Sagittarius A\u2217 (4.3 million solar masses) at galactic center",
      "Our Solar System orbits 26,000 light-years from center",
      "Dark matter halo extends ~300,000 light-years",
      "Andromeda Galaxy will collide with us in ~4.5 billion years",
      "Traveling at 552 km/s relative to cosmic microwave background",
      "Part of the Local Group — 54 galaxies bound by gravity"
    ]
  },
  andromedaGal: {
    name: "ANDROMEDA",
    symbol: "\u229B",
    subtitle: "Nearest Large Spiral Galaxy",
    info: "M31 — our cosmic neighbor, on a collision course with us",
    distance: "2.537 million light-years",
    diameter: "220,000 light-years",
    period: "~200 million years (galactic rotation)",
    dayLength: "N/A",
    temperature: "Varies",
    gravity: "N/A",
    moons: 0,
    atmosphere: "N/A",
    facts: [
      "Closest large galaxy to the Milky Way",
      "Contains ~1 trillion stars (2.5\u00d7 the Milky Way)",
      "Approaching at 110 km/s — collision in 4.5 billion years",
      "Merger will create 'Milkomeda', an elliptical galaxy",
      "Visible to the naked eye on dark nights as a fuzzy patch",
      "Has 2 prominent satellite galaxies: M32 and M110",
      "Edwin Hubble proved it's a separate galaxy in 1924",
      "Contains 26 known pulsars and thousands of globular clusters"
    ]
  },
  largeMagellanicCloud: {
    name: "LARGE MAGELLANIC CLOUD",
    symbol: "\u229B",
    subtitle: "Satellite Irregular Galaxy",
    info: "Closest satellite galaxy — orbiting the Milky Way",
    distance: "162,000 light-years",
    diameter: "14,000 light-years",
    period: "~1.5 billion years (orbit around Milky Way)",
    dayLength: "N/A",
    temperature: "Varies",
    gravity: "N/A",
    moons: 0,
    atmosphere: "N/A",
    facts: [
      "Closest irregular galaxy to Earth",
      "Contains the Tarantula Nebula — most active nearby star-forming region",
      "Home of R136a1 — most massive known star",
      "In gravitational orbit around the Milky Way",
      "Supernova SN 1987A was observed here in real-time",
      "Contains approximately 30 billion stars",
      "First catalogued by Ferdinand Magellan in 1519",
      "Connected to Milky Way by the Magellanic Stream gas bridge"
    ]
  },
  m87Galaxy: {
    name: "M87 GALAXY",
    symbol: "\u229B",
    subtitle: "Giant Elliptical Galaxy",
    info: "Home of M87\u2217 — first photographed black hole",
    distance: "53.5 million light-years",
    diameter: "980,000 light-years",
    period: "N/A",
    dayLength: "N/A",
    temperature: "Varies",
    gravity: "N/A",
    moons: 0,
    atmosphere: "N/A",
    facts: [
      "Giant elliptical galaxy at the heart of the Virgo Cluster",
      "Home to M87\u2217: 6.5 billion solar mass black hole",
      "Contains an estimated 1 trillion stars",
      "Ejects a 5,000 light-year plasma jet from its central BH",
      "Has over 15,000 globular clusters (Milky Way has ~150)",
      "One of the most massive galaxies in the local universe",
      "First observed by Charles Messier in 1781",
      "Dominant galaxy of the Virgo Supercluster"
    ]
  },
  // ── Kuiper Belt & Dwarf Planets ──
  kuiperSun: {
    name: "THE SUN (Distant View)",
    symbol: "\u2609",
    subtitle: "From 40+ AU Away",
    info: "Our Sun as seen from the Kuiper Belt — a very bright star among stars",
    distance: "~40 AU from Kuiper Belt objects",
    diameter: "1,392,000 km",
    period: "\u2014",
    dayLength: "25 Earth days",
    temperature: "5,500\u00b0C (surface)",
    gravity: "28g",
    moons: 0,
    atmosphere: "Hydrogen, Helium",
    facts: [
      "From Pluto, the Sun appears 1,000x dimmer than from Earth",
      "Still the brightest object in the Kuiper Belt sky by far",
      "Its gravity controls orbits out to ~100,000 AU (Oort Cloud)",
      "Light takes 5.5 hours to reach Pluto from the Sun",
      "From Sedna, the Sun appears no larger than a pinhead",
      "The Kuiper Belt extends from ~30 AU to ~50 AU",
      "Contains over 100,000 objects larger than 100 km",
      "Source of short-period comets that visit the inner solar system"
    ]
  },
  eris: {
    name: "ERIS",
    symbol: "\u2646",
    subtitle: "Most Massive Dwarf Planet",
    info: "The discovery of Eris caused Pluto's demotion to dwarf planet status",
    distance: "~96 AU (at aphelion)",
    diameter: "2,326 km (0.18x Earth)",
    period: "558 Earth years",
    dayLength: "25.9 hours",
    temperature: "-231\u00b0C (average)",
    gravity: "0.08g",
    moons: 1,
    atmosphere: "Thin nitrogen/methane (seasonal, collapses when far from Sun)",
    facts: [
      "Discovery in 2005 by Brown, Trujillo & Rabinowitz caused the 'Planet Wars'",
      "More massive than Pluto despite similar size \u2014 triggered Pluto's reclassification",
      "Named after the goddess of discord \u2014 fitting, given the controversy",
      "Has one moon: Dysnomia (named after Eris's daughter, spirit of lawlessness)",
      "Surface covered in methane ice, giving it a bright reflective appearance",
      "At aphelion it's 97 AU from the Sun \u2014 nearly 3x Pluto's distance",
      "Orbit is highly inclined (44\u00b0) relative to the ecliptic plane",
      "Atmosphere collapses and freezes onto surface as it moves away from Sun"
    ]
  },
  makemake: {
    name: "MAKEMAKE",
    symbol: "\u2646",
    subtitle: "Dwarf Planet of the Kuiper Belt",
    info: "Bright reddish world of methane ice — named after a Rapa Nui creator god",
    distance: "~52 AU (average)",
    diameter: "1,434 km (0.11x Earth)",
    period: "305.34 Earth years",
    dayLength: "22.8 hours",
    temperature: "-239\u00b0C",
    gravity: "0.05g",
    moons: 1,
    atmosphere: "Very thin (possibly none — uncertain)",
    facts: [
      "3rd largest dwarf planet in the Kuiper Belt after Eris and Pluto",
      "Named after the creator god of the Rapa Nui people of Easter Island",
      "Bright red-brown surface from tholins \u2014 complex organic molecules",
      "Covered in frozen methane, ethane and nitrogen",
      "Has one small dark moon: MK2, discovered 2016 by Hubble",
      "No atmosphere detected \u2014 unlike Pluto, it lacks nitrogen to sublimate",
      "One of the brightest Kuiper Belt objects after Pluto",
      "Was discovered 3 days after Easter 2005 \u2014 nearly named 'Easterbunny'"
    ]
  },
  haumea: {
    name: "HAUMEA",
    symbol: "\u2646",
    subtitle: "Fastest Spinning Dwarf Planet",
    info: "Football-shaped world spinning so fast it completes a day in just 4 hours",
    distance: "~43 AU (average)",
    diameter: "1,960 \u00d7 1,518 \u00d7 996 km (elongated ellipsoid)",
    period: "284.12 Earth years",
    dayLength: "3.9 hours (fastest large KBO rotation)",
    temperature: "-241\u00b0C",
    gravity: "0.044g",
    moons: 2,
    atmosphere: "None detected",
    facts: [
      "Spins so fast (once per 3.9 hours) that it's squashed into a football shape",
      "Has a ring system \u2014 only the 3rd small body known to have one",
      "Two moons: Hi'iaka and Namaka, named after Hawaiian sea goddesses",
      "Named after the Hawaiian goddess of childbirth and fertility",
      "Likely formed by a massive collision that spun it up and ejected the moons",
      "Surface covered in crystalline water ice, making it very bright",
      "Discovered simultaneously in 2004-2005 by Brown (USA) and Ortiz (Spain)",
      "Its elongated shape is unique among dwarf planets"
    ]
  },
  sedna: {
    name: "SEDNA",
    symbol: "\u2646",
    subtitle: "Most Distant Known Solar Object",
    info: "Deep space wanderer with an 11,400-year orbit — may hint at Planet Nine",
    distance: "84 AU (currently) — up to 936 AU at aphelion",
    diameter: "~1,000 km (estimated)",
    period: "~11,390 Earth years",
    dayLength: "~10 hours",
    temperature: "-240\u00b0C (one of coldest objects known)",
    gravity: "~0.04g",
    moons: 0,
    atmosphere: "None",
    facts: [
      "Discovered 2003 \u2014 most distant solar system body known at the time",
      "Named after the Inuit goddess of the sea",
      "Never comes closer than 76 AU \u2014 even at perihelion, far beyond Neptune",
      "Its strange orbit may indicate a distant unseen planet (Planet Nine) nudged it",
      "At aphelion it's 936 AU away \u2014 nearly 1/6 of a light-year from the Sun",
      "Surface is one of the reddest in the solar system \u2014 deep crimson color",
      "Orbit is so elliptical it belongs to the 'inner Oort Cloud'",
      "No confirmed moons, though its slow rotation is unexplained"
    ]
  },
  // ── Red Dwarfs ──
  proximaCentauri: {
    name: "PROXIMA CENTAURI",
    symbol: "\u2605",
    subtitle: "Nearest Star to Our Sun",
    info: "Ultra-cool red dwarf — closest star to the Solar System at 4.24 light-years",
    distance: "4.24 light-years",
    diameter: "214,900 km (0.15x Sun)",
    period: "\u2014",
    dayLength: "~83 Earth days",
    temperature: "3,042\u00b0C (surface)",
    gravity: "0.15g (surface)",
    moons: 0,
    atmosphere: "Hydrogen (M5.5-type red dwarf)",
    facts: [
      "Nearest star to our Solar System — part of Alpha Centauri triple system",
      "Host to at least 3 planets: b (confirmed), c (confirmed), d (2022)",
      "So dim it's invisible to the naked eye despite being our nearest neighbor",
      "Flares violently — powerful UV bursts that may strip planetary atmospheres",
      "A planet here would be tidally locked, one face always toward the star",
      "Red dwarfs like Proxima live for trillions of years (Sun lives ~10 billion)",
      "At Voyager speed, reaching Proxima would take ~76,000 years",
      "Breakthrough Starshot project aims to send a probe here within a century"
    ]
  },
  proximaB: {
    name: "PROXIMA CENTAURI b",
    symbol: "b",
    subtitle: "Potentially Habitable Exoplanet",
    info: "Best candidate for life outside our solar system — 1.27 Earth masses",
    distance: "4.24 light-years (7.5 million km from Proxima)",
    diameter: "~13,900 km (estimated rocky)",
    period: "11.19 Earth days",
    dayLength: "Tidally locked (11.19 days)",
    temperature: "-39\u00b0C average (estimated, no atmosphere confirmed)",
    gravity: "~1.1g (estimated)",
    moons: 0,
    atmosphere: "Unknown — JWST and ELT are primary investigation targets",
    facts: [
      "Confirmed exoplanet orbiting in the habitable zone of Proxima Centauri",
      "Only 7.5 million km from its star — 20x closer than Mercury to the Sun",
      "Receives similar energy from Proxima as Earth from the Sun",
      "Likely tidally locked: permanent dayside and nightside",
      "Stellar flares from Proxima may have stripped any atmosphere",
      "Mass: minimum 1.27 Earth masses (could be larger if tilted orbit)",
      "Discovered in 2016 via radial velocity method",
      "Closest potentially habitable exoplanet ever found"
    ]
  },
  proximaC: {
    name: "PROXIMA CENTAURI c",
    symbol: "c",
    subtitle: "Super-Earth Candidate",
    info: "Cold super-Earth on a long outer orbit — 7 Earth masses",
    distance: "4.24 light-years (1.49 AU from Proxima)",
    diameter: "~20,000 km (estimated super-Earth)",
    period: "1,928 Earth days (~5.3 years)",
    dayLength: "Tidally locked or slow rotation",
    temperature: "~-220\u00b0C (far from dim red dwarf)",
    gravity: "~2.0g (estimated)",
    moons: 0,
    atmosphere: "Likely frozen — too cold and far for liquid water",
    facts: [
      "Candidate super-Earth, ~7 times Earth's mass",
      "Orbits far outside the habitable zone — likely frozen",
      "Detected via radial velocity in 2020, confirmation ongoing",
      "Direct imaging attempts show a candidate in the right position",
      "Would make an excellent vantage point to view the Alpha Centauri system",
      "Outer orbit protects inner planet b from asteroid bombardment",
      "Temperature so low any atmosphere would be frozen solid",
      "Mass comparable to Neptune but likely denser and rockier"
    ]
  },
  proximaD: {
    name: "PROXIMA CENTAURI d",
    symbol: "d",
    subtitle: "Tiny Inner Sub-Earth",
    info: "Smallest exoplanet candidate — only 0.26 Earth masses",
    distance: "4.24 light-years (0.029 AU from Proxima)",
    diameter: "~8,000 km (sub-Earth, estimated)",
    period: "5.12 Earth days",
    dayLength: "Tidally locked (5.12 days)",
    temperature: "~87\u00b0C (dayside estimate, close orbit)",
    gravity: "~0.4g (estimated)",
    moons: 0,
    atmosphere: "Likely none — stellar wind at this distance is intense",
    facts: [
      "Discovered 2022 — one of the lightest exoplanets ever detected",
      "Only 0.26 Earth masses, less massive than Mars",
      "Orbits far inside the habitable zone — too hot for liquid water",
      "Radial velocity signal is tiny: star wobbles just 40 cm/s",
      "Shows Proxima Centauri is a rich planetary system",
      "Among the smallest exoplanets detectable with current instruments",
      "Subject to intense X-ray and UV radiation from stellar flares",
      "Existence confirmed independently in 2022 by multiple teams"
    ]
  },
  barnardStar: {
    name: "BARNARD'S STAR",
    symbol: "\u2605",
    subtitle: "Fastest Moving Star in the Sky",
    info: "2nd nearest star system — moves faster across the sky than any other",
    distance: "5.96 light-years",
    diameter: "~220,000 km (0.16x Sun)",
    period: "\u2014",
    dayLength: "~130 Earth days",
    temperature: "3,134\u00b0C (surface)",
    gravity: "0.14g (surface)",
    moons: 0,
    atmosphere: "Hydrogen (M4-type red dwarf)",
    facts: [
      "2nd nearest star system to Earth after Alpha Centauri/Proxima",
      "Moves 10.3 arcseconds per year — fastest proper motion of any star",
      "At its current speed, it will make its closest approach in ~10,000 years",
      "Named after E.E. Barnard who measured its motion in 1916",
      "Candidate planet b was announced 2018 then retracted — still debated",
      "One of the oldest stars in the Milky Way — ~10 billion years old",
      "Target of Project Daedalus (1970s British Interplanetary Society study)",
      "So dim it would appear as a faint red speck even from very close"
    ]
  },
  barnardPlanet: {
    name: "BARNARD'S STAR b",
    symbol: "b",
    subtitle: "Contested Super-Earth Candidate",
    info: "Debated cold super-Earth — detected then disputed, investigation ongoing",
    distance: "5.96 light-years (0.4 AU from Barnard's Star)",
    diameter: "~20,000 km (estimated super-Earth)",
    period: "232.8 Earth days",
    dayLength: "Unknown",
    temperature: "~-170\u00b0C (far outside habitable zone)",
    gravity: "~2.0g (estimated, if 3.2 Earth masses)",
    moons: 0,
    atmosphere: "Likely frozen — no liquid water possible at this distance",
    facts: [
      "Announced 2018 by Ribas et al. using combined radial velocity data",
      "Candidate planet, 3.2 Earth masses, orbiting beyond the snow line",
      "2021 follow-up study cast doubt — signal may be stellar activity",
      "Debate ongoing — illustrates difficulty of detecting tiny planets",
      "Would be a frozen world, like a super-Europa or super-Pluto",
      "Located near the snow line where water ice is stable",
      "If confirmed, would be closest super-Earth known to us",
      "Barnard's Star's age (~10 billion years) means any planet is very old"
    ]
  },
  wolf359: {
    name: "WOLF 359",
    symbol: "\u2605",
    subtitle: "Famous Red Dwarf Star",
    info: "6th nearest star — made famous by Star Trek's Battle of Wolf 359",
    distance: "7.86 light-years",
    diameter: "~157,000 km (0.11x Sun)",
    period: "\u2014",
    dayLength: "~Unknown",
    temperature: "2,800\u00b0C (surface)",
    gravity: "~0.1g (surface)",
    moons: 0,
    atmosphere: "Hydrogen (M6-type ultra-cool red dwarf)",
    facts: [
      "Made famous by Star Trek TNG: 'The Best of Both Worlds' (Borg battle)",
      "One of the smallest and dimmest stars known — barely above brown dwarf threshold",
      "Surface temperature is so cool it forms complex molecules in its atmosphere",
      "Flares intensely with UV and X-ray radiation despite its small size",
      "No confirmed planets — intense flaring makes habitability unlikely",
      "Only 0.09 solar masses — just 7% of the Sun's mass",
      "Luminosity is only 0.001% of the Sun (1,000x dimmer)",
      "Located in the constellation Leo, 6th nearest stellar system to Earth"
    ]
  },
  // ── White Dwarfs ──
  fortyEridaniA: {
    name: "40 ERIDANI A",
    symbol: "\u2609",
    subtitle: "K-Type Main Sequence Star",
    info: "Orange dwarf star — home to Spock's planet Vulcan in Star Trek lore",
    distance: "16.3 light-years",
    diameter: "985,000 km (0.71x Sun)",
    period: "\u2014",
    dayLength: "~43 Earth days",
    temperature: "5,100\u00b0C (surface)",
    gravity: "0.78g (surface)",
    moons: 0,
    atmosphere: "Hydrogen, helium",
    facts: [
      "Part of a triple star system with 40 Eri B and C",
      "Star Trek: Vulcan (Spock's home) was set here",
      "Slightly smaller and cooler than our Sun",
      "K-dwarf stars live up to 20 billion years",
      "40 Eridani B was the first white dwarf discovered (1910)",
      "Located in the constellation Eridanus",
      "One of the closest multiple-star systems to Earth",
      "K-type stars are prime targets in the search for life"
    ]
  },
  fortyEridaniB: {
    name: "40 ERIDANI B",
    symbol: "\u2609",
    subtitle: "White Dwarf Star",
    info: "First white dwarf identified — Earth-sized remnant of a dead star",
    distance: "16.3 light-years",
    diameter: "~12,700 km (0.99x Earth)",
    period: "247.9 years (orbit around 40 Eri A)",
    dayLength: "Unknown",
    temperature: "16,500\u00b0C (surface)",
    gravity: "~43,000g (surface)",
    moons: 0,
    atmosphere: "Pure hydrogen shell (DA white dwarf)",
    facts: [
      "First white dwarf ever identified — confirmed by W. Adams in 1914",
      "Mass: 0.59 solar masses packed into an Earth-sized sphere",
      "Orbited by 40 Eri C, a red dwarf, in a close pair",
      "Will cool into a black dwarf over trillions of years",
      "No ongoing nuclear fusion — pure gravitational compression heat",
      "Surface gravity 43,000x stronger than Earth's",
      "Spectral type DA — hydrogen atmosphere, no metal lines",
      "Astronomers use it to calibrate white dwarf cooling models"
    ]
  },
  procyonA: {
    name: "PROCYON A",
    symbol: "\u2609",
    subtitle: "F-Type Subgiant Star",
    info: "8th brightest star in the sky — slightly evolved yellow-white star",
    distance: "11.5 light-years",
    diameter: "2,050,000 km (1.48x Sun)",
    period: "\u2014",
    dayLength: "~23 Earth days",
    temperature: "6,530\u00b0C (surface)",
    gravity: "2.0g (surface)",
    moons: 0,
    atmosphere: "Hydrogen, helium",
    facts: [
      "8th brightest star in the night sky",
      "Greek: 'before the dog' \u2014 rises just before Sirius",
      "Slightly evolved off the main sequence, becoming a subgiant",
      "Will expand into a red giant in ~10 million years",
      "Companion Procyon B orbits it once every 40.8 years",
      "Located in the constellation Canis Minor",
      "One of the Sun's nearest stellar neighbors at 11.5 ly",
      "Visible from nearly every point on Earth"
    ]
  },
  procyonB: {
    name: "PROCYON B",
    symbol: "\u2609",
    subtitle: "White Dwarf Star",
    info: "Cool, dim white dwarf hidden in the glare of bright Procyon A",
    distance: "11.5 light-years",
    diameter: "~9,000 km (0.71x Earth)",
    period: "40.8 years (orbit around Procyon A)",
    dayLength: "Unknown",
    temperature: "7,740\u00b0C (surface)",
    gravity: "~200,000g (surface)",
    moons: 0,
    atmosphere: "Hydrogen (DQZ spectral type — carbon and metals detected)",
    facts: [
      "One of the nearest white dwarfs to Earth",
      "Its existence was predicted from Procyon A's wobble in 1844",
      "Finally directly observed in 1896 by John Schaeberle",
      "Mass: 0.6 solar masses in a sphere smaller than Earth",
      "One of the coolest white dwarfs studied in detail",
      "Has detectable carbon and metals from accreted material",
      "Orbit brings it as close as 8.9 AU and as far as 21 AU from Procyon A",
      "Procyon A's gravity keeps it in a stable 40.8-year orbit"
    ]
  },
}

// ── Physics configuration ────────────────────────────────────────────────────
// Coordinate system: Sun at (0,0), distances in pixels
// G and masses tuned for visual stability at 1200x1200 space

export const G = 100

// Start angles derived from CSS animation-delay / duration * 2PI
// e.g. Mercury: delay=-1s, duration=6s → 1/6 * 2PI ≈ 1.047 rad
export const bodyConfig = [
  // ── Sun ──
  {
    id: 'sun',
    mass: 10000,
    radius: 40,
    orbitRadius: 0,
    parent: null,
    domSelector: '.sun',
    color: '#ffcc00',
    trailMax: 0,
    startAngle: 0,
  },
  // ── Planets ──
  {
    id: 'mercury',
    mass: 0.01,
    radius: 6,
    orbitRadius: 70,
    parent: 'sun',
    domSelector: '.mercury',
    color: '#a5a5a5',
    trailMax: 400,
    startAngle: (1 / 6) * Math.PI * 2,       // delay -1s / 6s
  },
  {
    id: 'venus',
    mass: 0.05,
    radius: 11,
    orbitRadius: 105,
    parent: 'sun',
    domSelector: '.venus',
    color: '#e3bb76',
    trailMax: 500,
    startAngle: (4 / 6.1) * Math.PI * 2,     // delay -4s / 6.1s
  },
  {
    id: 'earth',
    mass: 5,
    radius: 12.5,
    orbitRadius: 150,
    parent: 'sun',
    domSelector: '.earth',
    color: '#2b82c9',
    trailMax: 600,
    startAngle: (2 / 10) * Math.PI * 2,      // delay -2s / 10s
  },
  {
    id: 'mars',
    mass: 2,
    radius: 9,
    orbitRadius: 195,
    parent: 'sun',
    domSelector: '.mars',
    color: '#e27b58',
    trailMax: 600,
    startAngle: (5 / 18.8) * Math.PI * 2,
  },
  {
    id: 'jupiter',
    mass: 50,
    radius: 25,
    orbitRadius: 275,
    parent: 'sun',
    domSelector: '.jupiter',
    color: '#d39c7e',
    trailMax: 600,
    startAngle: (10 / 40) * Math.PI * 2,
  },
  {
    id: 'saturn',
    mass: 30,
    radius: 22.5,
    orbitRadius: 350,
    parent: 'sun',
    domSelector: '.saturn',
    color: '#c5ab6e',
    trailMax: 600,
    startAngle: (15 / 60) * Math.PI * 2,
  },
  {
    id: 'uranus',
    mass: 10,
    radius: 15,
    orbitRadius: 425,
    parent: 'sun',
    domSelector: '.uranus',
    color: '#b3d1d1',
    trailMax: 600,
    startAngle: (20 / 80) * Math.PI * 2,
  },
  {
    id: 'neptune',
    mass: 10,
    radius: 15,
    orbitRadius: 480,
    parent: 'sun',
    domSelector: '.neptune',
    color: '#6081ff',
    trailMax: 600,
    startAngle: (30 / 120) * Math.PI * 2,
  },
  {
    id: 'pluto',
    mass: 0.5,
    radius: 5,
    orbitRadius: 550,
    parent: 'sun',
    domSelector: '.pluto',
    color: '#7f7f7f',
    trailMax: 600,
    startAngle: (40 / 150) * Math.PI * 2,
  },
  // ── Moons ──
  {
    id: 'moon',
    mass: 0.001,
    radius: 3,
    orbitRadius: 22.5,
    parent: 'earth',
    domSelector: '.moon',
    color: '#dddddd',
    trailMax: 200,
    startAngle: (1 / 2.7) * Math.PI * 2,
  },
  {
    id: 'phobos',
    mass: 0.0001,
    radius: 1.5,
    orbitRadius: 15,
    parent: 'mars',
    domSelector: '.phobos',
    color: '#9d8e87',
    trailMax: 150,
    startAngle: (0.5 / 1) * Math.PI * 2,
  },
  {
    id: 'deimos',
    mass: 0.0001,
    radius: 1,
    orbitRadius: 22.5,
    parent: 'mars',
    domSelector: '.deimos',
    color: '#9d8e87',
    trailMax: 150,
    startAngle: (1.5 / 3) * Math.PI * 2,
  },
  {
    id: 'io',
    mass: 0.001,
    radius: 2,
    orbitRadius: 35,
    parent: 'jupiter',
    domSelector: '.io',
    color: '#f9e231',
    trailMax: 150,
    startAngle: (0.5 / 2) * Math.PI * 2,
  },
  {
    id: 'europa',
    mass: 0.001,
    radius: 1.75,
    orbitRadius: 45,
    parent: 'jupiter',
    domSelector: '.europa',
    color: '#fdf5e6',
    trailMax: 150,
    startAngle: (1 / 4) * Math.PI * 2,
  },
  {
    id: 'ganymede',
    mass: 0.002,
    radius: 2.5,
    orbitRadius: 57.5,
    parent: 'jupiter',
    domSelector: '.ganymede',
    color: '#95877c',
    trailMax: 150,
    startAngle: (2 / 7) * Math.PI * 2,
  },
  {
    id: 'titan',
    mass: 0.002,
    radius: 3,
    orbitRadius: 60,
    parent: 'saturn',
    domSelector: '.titan',
    color: '#e3bb76',
    trailMax: 150,
    startAngle: (3 / 10) * Math.PI * 2,
  },
  {
    id: 'titania',
    mass: 0.001,
    radius: 1.5,
    orbitRadius: 25,
    parent: 'uranus',
    domSelector: '.titania',
    color: '#dcdcdc',
    trailMax: 150,
    startAngle: (1 / 5) * Math.PI * 2,
  },
  {
    id: 'triton',
    mass: 0.001,
    radius: 2,
    orbitRadius: 30,
    parent: 'neptune',
    domSelector: '.triton',
    color: '#d2f8f8',
    trailMax: 150,
    startAngle: (1 / 6) * Math.PI * 2,
    retrograde: true,
  },
  {
    id: 'charon',
    mass: 0.001,
    radius: 1,
    orbitRadius: 10,
    parent: 'pluto',
    domSelector: '.charon',
    color: '#a5a5a5',
    trailMax: 100,
    startAngle: (0.5 / 1) * Math.PI * 2,
    retrograde: true,
  },
]

// ── Scene Configurations ──────────────────────────────────────────────────
// Each scene defines which bodies to render and their physics configs

export const scenes = {
  solar: {
    id: 'solar',
    name: 'Solar System',
    icon: '\u2609',
    description: 'Our home planetary system',
    bodyIds: ['sun', 'mercury', 'venus', 'earth', 'mars', 'jupiter', 'saturn', 'uranus', 'neptune', 'pluto',
              'moon', 'phobos', 'deimos', 'io', 'europa', 'ganymede', 'titan', 'titania', 'triton', 'charon'],
    backgroundType: 'stars',
    scale: 1,
  },
  stellar: {
    id: 'stellar',
    name: 'Stellar Remnants',
    icon: '\u2726',
    description: 'End states of massive stars',
    bodyIds: ['siriusA', 'siriusB', 'velaPulsar', 'sagittariusA'],
    backgroundType: 'nebula',
    scale: 0.8,
  },
  exoplanets: {
    id: 'exoplanets',
    name: 'TRAPPIST-1',
    icon: '\u2727',
    description: 'Ultra-cool dwarf with 7 rocky worlds',
    bodyIds: ['trappist1', 'trappist1b', 'trappist1c', 'trappist1d', 'trappist1e', 'trappist1f', 'trappist1g', 'trappist1h'],
    backgroundType: 'deep',
    scale: 1.2,
  },
  blackholes: {
    id: 'blackholes',
    name: 'Black Holes',
    icon: '\u25C9',
    description: 'Cosmic gravitational monsters',
    bodyIds: ['ton618', 'm87bh', 'cygnusX1', 'hde226868'],
    backgroundType: 'blackhole',
    scale: 1,
  },
  supergiants: {
    id: 'supergiants',
    name: 'Supergiant Stars',
    icon: '\u2605',
    description: 'Monster stars nearing supernova',
    bodyIds: ['betelgeuse', 'vyCanisMajoris', 'r136a1'],
    backgroundType: 'nebula',
    scale: 1,
  },
  neutrons: {
    id: 'neutrons',
    name: 'Neutron Stars',
    icon: '\u2299',
    description: 'City-sized remnants of supernova explosions',
    bodyIds: ['velaPulsar', 'psrJ0348', 'psrJ0348Companion', 'magnetar'],
    backgroundType: 'deep',
    scale: 1,
  },
  galaxies: {
    id: 'galaxies',
    name: 'Galaxies',
    icon: '\u229B',
    description: 'Island universes across the cosmos',
    bodyIds: ['milkyWayGal', 'andromedaGal', 'largeMagellanicCloud', 'm87Galaxy'],
    backgroundType: 'galaxy',
    scale: 1,
  },
  whitedwarfs: {
    id: 'whitedwarfs',
    name: 'White Dwarfs',
    icon: '\u25CB',
    description: 'Stellar remnants — dead stars cooling for eternity',
    bodyIds: ['siriusA', 'siriusB', 'fortyEridaniA', 'fortyEridaniB', 'procyonA', 'procyonB'],
    backgroundType: 'deep',
    scale: 1,
  },
  reddwarfs: {
    id: 'reddwarfs',
    name: 'Red Dwarfs',
    icon: '\u2736',
    description: 'The most common stars — dim, ancient, long-lived',
    bodyIds: ['proximaCentauri', 'proximaD', 'proximaB', 'proximaC', 'barnardStar', 'barnardPlanet', 'wolf359'],
    backgroundType: 'nebula',
    scale: 1,
  },
  kuiperbelt: {
    id: 'kuiperbelt',
    name: 'Kuiper Belt',
    icon: '\u25CC',
    description: 'Frozen frontier — dwarf planets beyond Neptune',
    bodyIds: ['kuiperSun', 'plutoKB', 'charonKB', 'haumea', 'makemake', 'eris', 'sedna'],
    backgroundType: 'deep',
    scale: 1,
  },
}

// ── Scene-specific body configurations ─────────────────────────────────────
// Bodies not in solar system need special configs

export const sceneBodyConfigs = {
  // Stellar Remnants scene bodies
  siriusA: {
    id: 'siriusA',
    mass: 20000,
    radius: 45,
    orbitRadius: 0,
    parent: null,
    startX: -160,
    startY: 20,
    domSelector: '.sirius-a',
    color: '#aaccff',
    trailMax: 0,
    sceneType: 'stellar',
  },
  siriusB: {
    id: 'siriusB',
    mass: 0.01,
    radius: 8,
    orbitRadius: 120,
    parent: 'siriusA',
    domSelector: '.sirius-b',
    color: '#ffffff',
    trailMax: 400,
    startAngle: 0,
    sceneType: 'stellar',
  },
  velaPulsar: {
    id: 'velaPulsar',
    mass: 0,
    radius: 12,
    orbitRadius: 0,
    parent: null,
    startX: 20,
    startY: -200,
    domSelector: '.vela-pulsar',
    color: '#44aaff',
    trailMax: 0,
    pulseEffect: true,
    sceneType: 'stellar',
  },
  sagittariusA: {
    id: 'sagittariusA',
    mass: 0,
    radius: 60,
    orbitRadius: 0,
    parent: null,
    startX: 210,
    startY: 150,
    domSelector: '.sagittarius-a',
    color: '#000000',
    trailMax: 0,
    accretionDisk: true,
    sceneType: 'stellar',
  },
  // TRAPPIST-1 system bodies
  trappist1: {
    id: 'trappist1',
    mass: 800,
    radius: 25,
    orbitRadius: 0,
    parent: null,
    domSelector: '.trappist-1',
    color: '#ff6644',
    trailMax: 0,
    startAngle: 0,
    glowEffect: true,
    sceneType: 'exoplanets',
  },
  trappist1b: {
    id: 'trappist1b',
    mass: 0.8,
    radius: 9,
    orbitRadius: 50,
    parent: 'trappist1',
    domSelector: '.trappist-1b',
    color: '#cc8866',
    trailMax: 300,
    startAngle: 0,
    sceneType: 'exoplanets',
  },
  trappist1e: {
    id: 'trappist1e',
    mass: 0.7,
    radius: 7.5,
    orbitRadius: 85,
    parent: 'trappist1',
    domSelector: '.trappist-1e',
    color: '#66aa88',
    trailMax: 350,
    startAngle: Math.PI,
    sceneType: 'exoplanets',
  },
  trappist1c: {
    id: 'trappist1c',
    mass: 0.9,
    radius: 9,
    orbitRadius: 63,
    parent: 'trappist1',
    domSelector: '.trappist-1c',
    color: '#dd9966',
    trailMax: 300,
    startAngle: Math.PI * 0.5,
    sceneType: 'exoplanets',
  },
  trappist1d: {
    id: 'trappist1d',
    mass: 0.6,
    radius: 7,
    orbitRadius: 76,
    parent: 'trappist1',
    domSelector: '.trappist-1d',
    color: '#aabb88',
    trailMax: 320,
    startAngle: Math.PI * 1.2,
    sceneType: 'exoplanets',
  },
  trappist1f: {
    id: 'trappist1f',
    mass: 0.9,
    radius: 8.5,
    orbitRadius: 115,
    parent: 'trappist1',
    domSelector: '.trappist-1f',
    color: '#6688cc',
    trailMax: 400,
    startAngle: Math.PI * 1.5,
    sceneType: 'exoplanets',
  },
  trappist1g: {
    id: 'trappist1g',
    mass: 0.85,
    radius: 9.5,
    orbitRadius: 145,
    parent: 'trappist1',
    domSelector: '.trappist-1g',
    color: '#88aabb',
    trailMax: 450,
    startAngle: Math.PI * 0.3,
    sceneType: 'exoplanets',
  },
  trappist1h: {
    id: 'trappist1h',
    mass: 0.5,
    radius: 7,
    orbitRadius: 178,
    parent: 'trappist1',
    domSelector: '.trappist-1h',
    color: '#c0d8ee',
    trailMax: 500,
    startAngle: Math.PI * 0.8,
    sceneType: 'exoplanets',
  },

  // ── Black Holes scene ─────────────────────────────────────────────────────
  ton618: {
    id: 'ton618',
    mass: 0,
    radius: 90,
    orbitRadius: 0,
    parent: null,
    startX: 0,
    startY: 0,
    domSelector: '.ton-618',
    color: '#ff6600',
    trailMax: 0,
    accretionDisk: true,
    sceneType: 'blackholes',
  },
  m87bh: {
    id: 'm87bh',
    mass: 0,
    radius: 60,
    orbitRadius: 0,
    parent: null,
    startX: 270,
    startY: -110,
    domSelector: '.m87-bh',
    color: '#ff8800',
    trailMax: 0,
    accretionDisk: true,
    sceneType: 'blackholes',
  },
  cygnusX1: {
    id: 'cygnusX1',
    mass: 50000,
    radius: 22,
    orbitRadius: 0,
    parent: null,
    startX: -230,
    startY: 140,
    domSelector: '.cygnus-x1',
    color: '#cc4400',
    trailMax: 0,
    accretionDisk: true,
    sceneType: 'blackholes',
  },
  hde226868: {
    id: 'hde226868',
    mass: 0.01,
    radius: 20,
    orbitRadius: 80,
    parent: 'cygnusX1',
    startAngle: Math.PI / 3,
    domSelector: '.hde-226868',
    color: '#aaccff',
    trailMax: 350,
    sceneType: 'blackholes',
  },

  // ── Supergiant Stars scene ────────────────────────────────────────────────
  betelgeuse: {
    id: 'betelgeuse',
    mass: 0,
    radius: 100,
    orbitRadius: 0,
    parent: null,
    startX: 80,
    startY: 30,
    domSelector: '.betelgeuse',
    color: '#ff4400',
    trailMax: 0,
    glowEffect: true,
    sceneType: 'supergiants',
  },
  vyCanisMajoris: {
    id: 'vyCanisMajoris',
    mass: 0,
    radius: 130,
    orbitRadius: 0,
    parent: null,
    startX: -270,
    startY: 60,
    domSelector: '.vy-canis-majoris',
    color: '#cc2200',
    trailMax: 0,
    glowEffect: true,
    sceneType: 'supergiants',
  },
  r136a1: {
    id: 'r136a1',
    mass: 0,
    radius: 50,
    orbitRadius: 0,
    parent: null,
    startX: 260,
    startY: -110,
    domSelector: '.r136a1',
    color: '#aaccff',
    trailMax: 0,
    glowEffect: true,
    sceneType: 'supergiants',
  },

  // ── Neutron Stars scene ───────────────────────────────────────────────────
  psrJ0348: {
    id: 'psrJ0348',
    mass: 20000,
    radius: 14,
    orbitRadius: 0,
    parent: null,
    startX: -180,
    startY: 100,
    domSelector: '.psr-j0348',
    color: '#66aaff',
    trailMax: 0,
    pulseEffect: true,
    sceneType: 'neutrons',
  },
  psrJ0348Companion: {
    id: 'psrJ0348Companion',
    mass: 0.01,
    radius: 7,
    orbitRadius: 55,
    parent: 'psrJ0348',
    startAngle: Math.PI / 4,
    domSelector: '.psr-j0348-companion',
    color: '#e8e8ff',
    trailMax: 300,
    sceneType: 'neutrons',
  },
  magnetar: {
    id: 'magnetar',
    mass: 0,
    radius: 14,
    orbitRadius: 0,
    parent: null,
    startX: 200,
    startY: 100,
    domSelector: '.magnetar',
    color: '#cc44ff',
    trailMax: 0,
    pulseEffect: true,
    sceneType: 'neutrons',
  },

  // ── Galaxies scene ────────────────────────────────────────────────────────
  milkyWayGal: {
    id: 'milkyWayGal',
    mass: 0,
    radius: 100,
    orbitRadius: 0,
    parent: null,
    startX: 30,
    startY: 30,
    domSelector: '.milky-way',
    color: '#ffe8b0',
    trailMax: 0,
    sceneType: 'galaxies',
  },
  andromedaGal: {
    id: 'andromedaGal',
    mass: 0,
    radius: 120,
    orbitRadius: 0,
    parent: null,
    startX: 290,
    startY: -100,
    domSelector: '.andromeda',
    color: '#c8d8ff',
    trailMax: 0,
    sceneType: 'galaxies',
  },
  largeMagellanicCloud: {
    id: 'largeMagellanicCloud',
    mass: 0,
    radius: 60,
    orbitRadius: 0,
    parent: null,
    startX: -200,
    startY: 200,
    domSelector: '.large-magellanic-cloud',
    color: '#d8e8ff',
    trailMax: 0,
    sceneType: 'galaxies',
  },
  m87Galaxy: {
    id: 'm87Galaxy',
    mass: 0,
    radius: 80,
    orbitRadius: 0,
    parent: null,
    startX: -270,
    startY: -150,
    domSelector: '.m87-galaxy',
    color: '#ffcc88',
    trailMax: 0,
    sceneType: 'galaxies',
  },

  // ── Kuiper Belt scene ─────────────────────────────────────────────────────
  kuiperSun: {
    id: 'kuiperSun',
    mass: 10000,
    radius: 10,
    orbitRadius: 0,
    parent: null,
    startX: 0,
    startY: 0,
    domSelector: '.kuiper-sun',
    color: '#ffcc44',
    trailMax: 0,
    sceneType: 'kuiperbelt',
  },
  plutoKB: {
    id: 'plutoKB',
    mass: 5,
    radius: 8,
    orbitRadius: 168,
    parent: 'kuiperSun',
    startAngle: 0,
    domSelector: '.pluto-kb',
    color: '#c4a882',
    trailMax: 500,
    sceneType: 'kuiperbelt',
  },
  charonKB: {
    id: 'charonKB',
    mass: 0.5,
    radius: 5,
    orbitRadius: 20,
    parent: 'plutoKB',
    startAngle: Math.PI,
    domSelector: '.charon-kb',
    color: '#a0a0b0',
    trailMax: 150,
    sceneType: 'kuiperbelt',
  },
  haumea: {
    id: 'haumea',
    mass: 3,
    radius: 9,
    orbitRadius: 183,
    parent: 'kuiperSun',
    startAngle: Math.PI * 0.42,
    domSelector: '.haumea',
    color: '#e8e0cc',
    trailMax: 520,
    sceneType: 'kuiperbelt',
  },
  makemake: {
    id: 'makemake',
    mass: 3,
    radius: 8,
    orbitRadius: 196,
    parent: 'kuiperSun',
    startAngle: Math.PI * 0.84,
    domSelector: '.makemake',
    color: '#c08060',
    trailMax: 540,
    sceneType: 'kuiperbelt',
  },
  eris: {
    id: 'eris',
    mass: 6,
    radius: 9,
    orbitRadius: 225,
    parent: 'kuiperSun',
    startAngle: Math.PI * 1.35,
    domSelector: '.eris',
    color: '#d8d0c8',
    trailMax: 580,
    sceneType: 'kuiperbelt',
  },
  sedna: {
    id: 'sedna',
    mass: 1,
    radius: 6,
    orbitRadius: 268,
    parent: 'kuiperSun',
    startAngle: Math.PI * 1.75,
    domSelector: '.sedna',
    color: '#cc4422',
    trailMax: 600,
    sceneType: 'kuiperbelt',
  },

  // ── Red Dwarfs scene ─────────────────────────────────────────────────────
  proximaCentauri: {
    id: 'proximaCentauri',
    mass: 3000,
    radius: 18,
    orbitRadius: 0,
    parent: null,
    startX: -180,
    startY: -30,
    domSelector: '.proxima-centauri',
    color: '#ff4422',
    trailMax: 0,
    glowEffect: true,
    sceneType: 'reddwarfs',
  },
  proximaD: {
    id: 'proximaD',
    mass: 0.1,
    radius: 4,
    orbitRadius: 40,
    parent: 'proximaCentauri',
    startAngle: Math.PI * 0.3,
    domSelector: '.proxima-d',
    color: '#cc8855',
    trailMax: 200,
    sceneType: 'reddwarfs',
  },
  proximaB: {
    id: 'proximaB',
    mass: 0.5,
    radius: 7,
    orbitRadius: 72,
    parent: 'proximaCentauri',
    startAngle: Math.PI * 1.1,
    domSelector: '.proxima-b',
    color: '#6699aa',
    trailMax: 280,
    sceneType: 'reddwarfs',
  },
  proximaC: {
    id: 'proximaC',
    mass: 1.0,
    radius: 10,
    orbitRadius: 140,
    parent: 'proximaCentauri',
    startAngle: Math.PI * 0.6,
    domSelector: '.proxima-c',
    color: '#5577aa',
    trailMax: 380,
    sceneType: 'reddwarfs',
  },
  barnardStar: {
    id: 'barnardStar',
    mass: 3200,
    radius: 16,
    orbitRadius: 0,
    parent: null,
    startX: 220,
    startY: -150,
    domSelector: '.barnard-star',
    color: '#ff3300',
    trailMax: 0,
    glowEffect: true,
    sceneType: 'reddwarfs',
  },
  barnardPlanet: {
    id: 'barnardPlanet',
    mass: 0.5,
    radius: 10,
    orbitRadius: 90,
    parent: 'barnardStar',
    startAngle: Math.PI * 1.6,
    domSelector: '.barnard-planet',
    color: '#557788',
    trailMax: 320,
    sceneType: 'reddwarfs',
  },
  wolf359: {
    id: 'wolf359',
    mass: 0,
    radius: 14,
    orbitRadius: 0,
    parent: null,
    startX: 60,
    startY: 220,
    domSelector: '.wolf-359',
    color: '#cc2200',
    trailMax: 0,
    glowEffect: true,
    sceneType: 'reddwarfs',
  },

  // ── White Dwarfs scene ────────────────────────────────────────────────────
  // siriusA and siriusB configs are reused from stellar scene (same ids)
  fortyEridaniA: {
    id: 'fortyEridaniA',
    mass: 12000,
    radius: 35,
    orbitRadius: 0,
    parent: null,
    startX: 220,
    startY: -150,
    domSelector: '.forty-eridani-a',
    color: '#ffaa66',
    trailMax: 0,
    sceneType: 'whitedwarfs',
  },
  fortyEridaniB: {
    id: 'fortyEridaniB',
    mass: 0.01,
    radius: 6,
    orbitRadius: 100,
    parent: 'fortyEridaniA',
    startAngle: Math.PI * 0.7,
    domSelector: '.forty-eridani-b',
    color: '#ffffff',
    trailMax: 350,
    sceneType: 'whitedwarfs',
  },
  procyonA: {
    id: 'procyonA',
    mass: 15000,
    radius: 40,
    orbitRadius: 0,
    parent: null,
    startX: 100,
    startY: 200,
    domSelector: '.procyon-a',
    color: '#ffeebb',
    trailMax: 0,
    sceneType: 'whitedwarfs',
  },
  procyonB: {
    id: 'procyonB',
    mass: 0.01,
    radius: 5,
    orbitRadius: 85,
    parent: 'procyonA',
    startAngle: Math.PI * 1.4,
    domSelector: '.procyon-b',
    color: '#f0f0f0',
    trailMax: 300,
    sceneType: 'whitedwarfs',
  },
}
